### PR TITLE
Check for empty pr before calling GetCombinedStatus

### LINKED ISSUE #12902: pr-status failure: failed to get the combined status: return code not 2XX: 404 Not Found
/assign @Katharine @cjwagner 

```yaml
{
 insertId:  "1ofdh3g19swcyr"  
 jsonPayload: {
  client:  "pr-status"   
  component:  "deck"   
  error:  "failed to get the combined status: return code not 2XX: 404 Not Found"   
  level:  "error"   
  msg:  "Error Error with getting head context of pr."   
 }
 labels: {…}  
 logName:  "projects/k8s-prow/logs/deck"  
 receiveTimestamp:  "2019-06-05T17:33:21.115116636Z"  
 resource: {…}  
 severity:  "ERROR"  
 timestamp:  "2019-06-05T17:33:17Z"  
}
```

### PR DESCRIPTION
**Pull request by matthyx**
Fixes #12902

### CODE REVIEW

File: prow/prstatus/prstatus.go [hunk 1]
```diff
@@ -323,7 +323,11 @@ func (da *DashboardAgent) QueryPullRequests(ctx context.Context, ghc githubClien
 func (da *DashboardAgent) GetHeadContexts(ghc githubClient, pr PullRequest) ([]Context, error) {
 	org := string(pr.Repository.Owner.Login)
 	repo := string(pr.Repository.Name)
-	combined, err := ghc.GetCombinedStatus(org, repo, string(pr.HeadRefOID))
+	ref := string(pr.HeadRefOID)
+	if org == "" || repo == "" || ref == "" {
+		return nil, fmt.Errorf("combined status asked for empty pull request: %v", pr)
```
Comment (stevekuznetsov) [inline prow/prstatus/prstatus.go]: This seems OK but is symptomatic of bad caller behavior so I think it would be good to also dig into why someone is sending empty `pr` objects.

Comment (matthyx) [reply prow/prstatus/prstatus.go]: Do you mean check with GitHub, or check earlier in the code - perhaps in `HandlePrStatus` or `QueryPullRequests`?

Comment (stevekuznetsov) [reply prow/prstatus/prstatus.go]: Earlier in the code -- unless we think we're getting empty objects from GitHub, which I don't think is the case.

Comment (matthyx) [reply prow/prstatus/prstatus.go]: But @stevekuznetsov I think this is exactly what @cjwagner meant here: https://github.com/kubernetes/test-infra/issues/12902#issuecomment-499200246

Comment (stevekuznetsov) [reply prow/prstatus/prstatus.go]: Err but that is upstream of this callsite, right? What calls `GetHeadContexts` with an empty `pr`? I guess it does make sense to be defensive _here_, maybe, but I would like it more to catch that where we initialize the `nil` value for the PR in the first place.

Comment (matthyx) [reply prow/prstatus/prstatus.go]: Alright, now I understand what you meant :)

**Comment by matthyx** [comment]
@stevekuznetsov PTAL, I now prune them directly in `QueryPullRequests`
