### PR TITLE
inform user when prow fails to reopen an issue or PR

### LINKED ISSUE #4786: Prow plugins: handle deleted branches / un-re-open-able PRs
At the very least the reopen plugin should gracefully handle attempts to reopen a PR with a deleted branches with an error reply so us foolish humans notice :-)
ref: https://github.com/kubernetes/kubernetes.github.io/pull/3711#issuecomment-332741407
/cc @xiangpengzhao

### PR DESCRIPTION
**Pull request by BenTheElder**
fixes #4786

### CODE REVIEW

**Comment by BenTheElder** [comment]
/area prow
we might want to scope down which errors are passed to the user or change the formatting
/shrug

**Comment by krzyzacy** [comment]
add something to the test that if we fail to reopen, we create a comment?

**Comment by BenTheElder** [comment]
@krzyzacy sure, I want to see if this is how we want to handle it though. I'm not sure this is the right solution but we should probably signal the user somehow when we attempt to re-open and fail.

**Comment by krzyzacy** [comment]
yeah agree that a command should give feedback upon failures

File: prow/plugins/reopen/reopen.go [hunk 1]
```diff
@@ -74,9 +75,19 @@ func handle(gc githubClient, log *logrus.Entry, e *github.GenericCommentEvent) e
 
 	if e.IsPR {
 		log.Info("Re-opening PR.")
-		return gc.ReopenPR(org, repo, number)
+		err := gc.ReopenPR(org, repo, number)
+		if err != nil {
+			resp := fmt.Sprintf("failed to re-open PR: %s", err)
```
Comment (cjwagner) [inline prow/plugins/reopen/reopen.go]: As is, the error message looks like:
```
"status code 422 not one of [200], body: {"message":"Validation Failed","errors":[{"resource":"PullRequest","code":"custom","field":"state","message":"state cannot be changed. The bump_kubernetes_to_1.8 branch was force-pushed or recreated."}],"documentation_url":"https://developer.github.com/v3/pulls/#update-a-pull-request"}"
```
which isn't formatted very nicely for a github comment.
If we are going to include the error text in the comment we might want to specifically handle the 422 error in `ReopenPR` and `ReopenIssue` and return a better message in that case.

I think a better alternative to using the error text is to change the signature of `ReopenPR` and `ReopenIssue` to return `(bool, error)` where the bool indicates whether the reopen was successful. A status of 422 would be treated as not an error, and `(false, nil)` would be returned indicating that the reopen failed and we need to leave a comment. This would distinguish the 'acceptable' error case from the other error cases which would return `(false, <non-nil-error>)` and should not result in comments being created.

Comment (BenTheElder) [reply prow/plugins/reopen/reopen.go]: Yeah I agree that the formatting right now would not be ideal but are we just not going to comment if the re-open fails for some other reason?

Comment (spxtr) [reply prow/plugins/reopen/reopen.go]: That would work. I think it's a bit more idiomatic to return just `error` but use a special error type that can be checked by the user. We do this for [assign and unassign](https://github.com/kubernetes/test-infra/blob/62ab514cbd6330af87c505c6cd1ccaf48345e8c8/prow/github/client.go#L613-L685) and it works well.

Comment (spxtr) [reply prow/plugins/reopen/reopen.go]: > Yeah I agree that the formatting right now would not be ideal but are we just not going to comment if the re-open fails for some other reason?

There is a general policy in prow to only comment for "expected" failures, whatever that means. For unexpected failures we should just log it, and maybe fire an alert if there are lots of them. It might be worth revisiting this policy.

Comment (BenTheElder) [reply prow/plugins/reopen/reopen.go]: Implementing the custom error type, which is definitely more idiomatic.

File: prow/github/client.go [hunk 2]
```diff
@@ -795,6 +819,12 @@ func (c *Client) ReopenIssue(org, repo string, number int) error {
 		requestBody: map[string]string{"state": "open"},
 		exitCodes:   []int{200},
 	}, nil)
+	requestErr, ok := err.(requestError)
+	if ok && strings.Contains(requestErr.Message, "state cannot be changed.") {
```
Comment (BenTheElder) [inline prow/github/client.go]: oops this is not right, this is in one of the sub errors...

File: prow/github/client.go [hunk 3]
```diff
@@ -819,6 +849,12 @@ func (c *Client) ReopenPR(org, repo string, number int) error {
...
```
Comment (xiangpengzhao) [inline prow/github/client.go]: nit: it'd be good to define "state cannot be changed." as a const string in case it changes in the future.

Comment (BenTheElder) [reply prow/github/client.go]: done

File: prow/github/client.go (hunk 2 above)
Comment (BenTheElder) [reply prow/github/client.go]: fixed

File: prow/plugins/reopen/reopen.go (hunk 1 above)
Comment (BenTheElder) [reply prow/plugins/reopen/reopen.go]: I'm extracting the actual "state cannot be changed. ..." message now

File: prow/github/types.go [hunk 4]
```diff
@@ -30,14 +30,26 @@ const (
...
+	ReactionConfused                  = "confused"
+	ReactionHeart                     = "heart"
+	ReactionHooray                    = "hooray"
+	stateCannotBeChangedMessagePrefix = "state cannot be changed."
 )
 
+// https://developer.github.com/v3/#client-errors
+type ClientError struct {
+	Message string `json:"message"`
+	Errors  []struct {
```
Comment (BenTheElder) [inline prow/github/types.go]: this is possibly a bit un-idiomatic but GitHub doesn't even name these and they do have a different """schema""" than the parent type..

**Comment by BenTheElder** [comment]
:snowflake: 
/retest
/lint

File: prow/github/client.go [hunk 5]
```diff
@@ -795,6 +824,16 @@ func (c *Client) ReopenIssue(org, repo string, number int) error {
 		requestBody: map[string]string{"state": "open"},
 		exitCodes:   []int{200},
 	}, nil)
+	requestErr, ok := err.(requestError)
```
Comment (cjwagner) [inline prow/github/client.go]: Instead of copying this code between `ReopenPR` and `ReopenIssue` you could move it to a function that accepts an error and returns an error of the appropriate type.

File: prow/plugins/reopen/reopen.go [hunk 6]
```diff
@@ -74,9 +75,19 @@ func handle(gc githubClient, log *logrus.Entry, e *github.GenericCommentEvent) e
 
 	if e.IsPR {
 		log.Info("Re-opening PR.")
-		return gc.ReopenPR(org, repo, number)
+		err := gc.ReopenPR(org, repo, number)
+		if err != nil {
```
Comment (cjwagner) [inline prow/plugins/reopen/reopen.go]: This will still create a comment for any error type.
This conditional and the analogous one bellow should require that the error is a `StateCannotBeChanged` error. See the [assign plugin](https://github.com/kubernetes/test-infra/blob/master/prow/plugins/assign/assign.go#L125) for an example.

Comment (BenTheElder) [reply prow/plugins/reopen/reopen.go]: oops yes, I meant to check the error type :man_facepalming:

File: prow/github/client.go (hunk 5 above)
Comment (BenTheElder) [reply prow/github/client.go]: done

File: prow/plugins/reopen/reopen.go (hunk 6 above)
Comment (BenTheElder) [reply prow/plugins/reopen/reopen.go]: done

File: prow/plugins/reopen/reopen.go [hunk 7]
```diff
@@ -74,9 +75,23 @@ func handle(gc githubClient, log *logrus.Entry, e *github.GenericCommentEvent) e
...
+		}
+	} else {
+		log.Info("Re-opening issue.")
+		if err := gc.ReopenIssue(org, repo, number); err != nil {
+			if scbc, ok := err.(github.StateCannotBeChanged); ok {
+				resp := fmt.Sprintf("failed to re-open Issue: %s", scbc)
+				return gc.CreateComment(org, repo, number, plugins.FormatResponseRaw(e.Body, e.HTMLURL, e.User.Login, resp))
+			}
+			return err
+		}
```
Comment (BenTheElder) [inline prow/plugins/reopen/reopen.go]: er no, this should return the err or nil always

Comment (BenTheElder) [reply prow/plugins/reopen/reopen.go]: moved this back closer to the original code.

File: prow/plugins/reopen/reopen.go [hunk 8]
```diff
@@ -74,9 +75,23 @@ func handle(gc githubClient, log *logrus.Entry, e *github.GenericCommentEvent) e
 
 	if e.IsPR {
 		log.Info("Re-opening PR.")
-		return gc.ReopenPR(org, repo, number)
+		err := gc.ReopenPR(org, repo, number)
+		if err != nil {
+			if scbc, ok := err.(github.StateCannotBeChanged); ok {
+				resp := fmt.Sprintf("failed to re-open PR: %s", scbc)
```
Comment (cjwagner) [inline prow/plugins/reopen/reopen.go]: This and bellow should be `%v` instead of `%s`.

Comment (BenTheElder) [reply prow/plugins/reopen/reopen.go]: done.

**Comment by krzyzacy** [comment]
bump hook?

File: prow/github/client.go [hunk 9]
```diff
@@ -795,7 +839,7 @@ func (c *Client) ReopenIssue(org, repo string, number int) error {
 		requestBody: map[string]string{"state": "open"},
 		exitCodes:   []int{200},
 	}, nil)
-	return err
+	return stateCannotBeChangedOrOriginalError(err)
```
Comment (spxtr) [inline prow/github/client.go]: Instead of this, add the possible failing exit codes to the input to `c.request`, then handle them. See how it is done in `AssignIssue`.

File: prow/github/client.go [hunk 10]
```diff
@@ -786,6 +802,34 @@ func (c *Client) CloseIssue(org, repo string, number int) error {
...
+
+// StateCannotBeChanged implements error
+var _ error = (*StateCannotBeChanged)(nil)
+
+// convert to a StateCannotBeChanged if appropriate or else return the original error
+func stateCannotBeChangedOrOriginalError(err error) error {
+	requestErr, ok := err.(requestError)
+	if ok && len(requestErr.Errors) > 0 {
+		for _, subErr := range requestErr.Errors {
+			if strings.Contains(subErr.Message, stateCannotBeChangedMessagePrefix) {
```
Comment (spxtr) [inline prow/github/client.go]: This will break anytime GitHub changes their messages. Instead, we should be relying on the status code, which should be more reliable.

**Comment by BenTheElder** [comment]
I want to extract and report this ClientError-sub-error-message and report
it to the user so AFAICT I would still need to do this search somewhere.
This seemed like the most reasonable place to do so.

File: prow/github/client.go [hunk 11]
```diff
@@ -114,6 +114,15 @@ type request struct {
 	exitCodes   []int
 }
 
+type requestError struct {
```
Comment (spxtr) [inline prow/github/client.go]: Are all request errors guaranteed to be this structure?

**Comment by spxtr** [comment]
I don't think you should need to do the search. You can still extract and report the message without relying on this prefix not changing.

File: prow/github/client.go (hunk 11 above)
Comment (BenTheElder) [reply prow/github/client.go]: yes, if it can unmarshal the ClientError?

**Comment by BenTheElder** [comment]
> I don't think you should need to do the search. You can still extract and report the message without relying on this prefix not changing.

We only want to report _that_ error though.

File: prow/github/types.go [hunk 12]
```diff
@@ -30,14 +30,26 @@ const (
...
-	ReactionConfused   = "confused"
-	ReactionHeart      = "heart"
-	ReactionHooray     = "hooray"
+	ReactionThumbsUp                  = "+1"
+	ReactionThumbsDown                = "-1"
+	ReactionLaugh                     = "laugh"
+	ReactionConfused                  = "confused"
+	ReactionHeart                     = "heart"
+	ReactionHooray                    = "hooray"
+	stateCannotBeChangedMessagePrefix = "state cannot be changed."
```
Comment (spxtr) [inline prow/github/types.go]: This shouldn't be in the same `const` block as the reactions.
