### PR TITLE
Make Gerrit reporter respect report field on prow jobs

### LINKED ISSUE #17419: Gerrit controller does not respect `report: false` on ProwJobs.
**What happened**:
Prow's allows for a `skip_report` field to be specified in job config and that is inverted into a `report` field on created ProwJobs. This field is respected by GitHub reporting and prevents including the job result in comments or status contexts. The gerrit controller doesn't appear to respect this field.

**What you expected to happen**:
- It should be a config error to configure gerrit report labels with `skip_report: true`
- The Gerrit controller should not report `report: false` jobs to Gerrit via comments nor labels.

**How to reproduce it (as minimally and precisely as possible)**:
Configure a gerrit job with `skip_report: true` and a gerrit report label annotation.

**Anything else we need to know?**:
I think this can currently be worked around by omitting all gerrit report label annotation.

/help

### PR DESCRIPTION
**Pull request by adshmh**
Closes #17419

### CODE REVIEW

**Comment by fejta** [comment]
/uncc @fejta @michelle192837 
/assign @cjwagner 

Thanks for fixing this!

File: prow/config/config.go [hunk 1]
```diff
@@ -1915,10 +1915,18 @@ func validateTriggering(job Presubmit) error {
 	return nil
 }
 
-func validateReporting(r Reporter) error {
+func validateReporting(j JobBase, r Reporter) error {
 	if !r.SkipReport && r.Context == "" {
 		return errors.New("job is set to report but has no context configured")
 	}
+	if !r.SkipReport {
```
Comment (fejta) [inline prow/config/config.go:1922]: What happens when !SkipReport && len(j.Labels) == 0?

File: prow/gerrit/adapter/adapter.go [hunk 2]
```diff
@@ -182,7 +182,11 @@ func (c *Controller) ProcessChange(instance string, change client.ChangeInfo) er
 		return fmt.Errorf("failed to get SHA from base branch: %v", err)
 	}
 
-	triggeredJobs := []string{}
+	type triggeredJob struct {
+		name   string
+		report bool
+	}
+	triggeredJobs := []triggeredJob{}
```
Comment (fejta) [inline prow/gerrit/adapter/adapter.go:189]: You are not initializing anything so use `var triggeredJobs []triggeredJob`

File: prow/gerrit/adapter/adapter_test.go [hunk 3]
```diff
@@ -704,18 +763,18 @@ func TestProcessChange(t *testing.T) {
...
 
-		testInstance := "https://gerrit"
 		fakeProwJobClient := prowfake.NewSimpleClientset()
 		fakeLastSync := client.LastSyncState{testInstance: map[string]time.Time{}}
 
 		for _, tc := range testcases {
 			fakeLastSync[testInstance][tc.change.Project] = timeNow.Add(-time.Minute)
 		}
 
+		gc := &fgc{}
```
Comment (fejta) [inline prow/gerrit/adapter/adapter_test.go:773]: Similar to above I would consider `var gc fgc` (and `gc: &gc` below) to be better practice as we never set gc to nil so there's no need to have to deal with pointers.

File: prow/gerrit/adapter/adapter_test.go [hunk 4]
```diff
@@ -757,5 +816,10 @@ func TestProcessChange(t *testing.T) {
 				t.Errorf("tc %s - BaseSHA should be abc, got %s", tc.name, prowjobs[0].Spec.Refs.BaseSHA)
 			}
 		}
+		if tc.shouldSkipReport {
+			if gc.reviews > 0 {
+				t.Errorf("tc %s - expected no comments, got: %d", tc.name, gc.reviews)
```
Comment (fejta) [inline prow/gerrit/adapter/adapter_test.go:821]: Ideally we refactor this unit test to match modern practices, aka

```golang
// deprecated
for _, tc := range testCases {
  // whatever
  tc.Errorf("tc %s ...", tc.name)
}

// expected
for _, tc := range testCases {
  t.Run(tc.name, func(t *testing.T) {
    t.Error("...") // name automatically appended
  }
}
```

This makes for better unit tests: cases run in parallel which make them faster as well as more likely to be hermetic.

Typically I convert test functions that still use the deprecated pattern when I'm modifying them (feel free to pass if you don't feel up to it though).

File: prow/gerrit/adapter/adapter.go [hunk 5]
```diff
@@ -293,19 +297,28 @@ func (c *Controller) ProcessChange(instance string, change client.ChangeInfo) er
...
+			})
 		}
 	}
 
+	var report bool
 	if len(triggeredJobs) > 0 {
-		// comment back to gerrit
-		message := fmt.Sprintf("Triggered %d prow jobs:", len(triggeredJobs))
+		// comment back to gerrit if Report is set for any of the jobs
+		message := fmt.Sprintf("Triggered %d prow jobs (the following list only includes jobs which do not suppress reporting):", len(triggeredJobs))
```
Comment (cjwagner) [inline prow/gerrit/adapter/adapter.go:310]: nit: Something like `(%d suppressed reporting)` would be a little more concise and informative.

File: prow/gerrit/adapter/adapter_test.go (hunk 3 above)
Comment (cjwagner) [reply prow/gerrit/adapter/adapter_test.go:773]: FYI I think you also need to call [`t.Parallel()`](https://golang.org/pkg/testing/#T.Parallel) at the beginning of the anonymous run function if you want the test cases to run in parallel. ref: https://golang.org/pkg/testing/#hdr-Subtests_and_Sub_benchmarks

File: prow/config/config.go (hunk 1 above)
Comment (cjwagner) [reply prow/config/config.go:1922]: My understanding is that labels are used to control voting and grouping jobs together to aggregate job reporting. Setting the report label to the empty string causes a job to report immediately when it completes without aggregation (https://github.com/kubernetes/test-infra/pull/15596).  Omitting the report label altogether causes the default label of "Code-Review" to be used (should default to "Verified" IMO).
So for all possible states of the gerrit report label (populated, empty string, omitted) we still comment to Gerrit. I think skip_report then can control if we comment at all, but we should probably only allow skip_report when the gerrit report label is set to the empty label since we need to comment to vote on a label.

I think @amwat and @krzyzacy know the most about Gerrit reporting and labels. Is the above accurate? Do you have thoughts on how this config should work?

File: prow/gerrit/adapter/adapter_test.go (hunk 4 above)
Comment (cjwagner) [reply prow/gerrit/adapter/adapter_test.go:821]: FYI I think you also need to call [`t.Parallel()`](https://golang.org/pkg/testing/#T.Parallel) at the beginning of the anonymous run function if you want the test cases to run in parallel. ref: https://golang.org/pkg/testing/#hdr-Subtests_and_Sub_benchmarks

File: prow/config/config.go (hunk 1 above)
Comment (amwat) [reply prow/config/config.go:1922]: Yes, that summary is accurate. also +1 to default verified (that is the intent of that label: https://gerrit-review.googlesource.com/Documentation/config-labels.html#label_Verified) the only problem is that verified "-1" is blocking by default and code-review is not, maybe after we have this skip-report feature Verified could be a sane default.

In terms of config, I guess i'm not sure what we want to achieve by skip-report, specifically whether we just want to 
1. skip reporting on a label but still show up in comments, 
2. or just not report at all to gerrit in any way.

If 2. then we can just return false here when skip-report is set (and exclude it from the selector)
https://github.com/kubernetes/test-infra/blob/6e7f9252d5fae7d74fd9ffabe9175078240000ca/prow/crier/reporters/gerrit/reporter.go#L104-L105

If 1. then forcing gerrit-report label to be empty makes sense.

Comment (adshmh) [reply prow/config/config.go:1922]: Thank you for the reviews. I have updated the PR to allow `skip_report` only if the Gerrit report label is set to empty or is omitted. I think the ignoring of `skip_report` was caused by the following: 

https://github.com/kubernetes/test-infra/blob/b5246a13a917f003450af87d15a94ff2dbc711f1/prow/gerrit/adapter/adapter.go#L307-L309



Crier will not run any reporters for a job which has `skip_report` set:
https://github.com/kubernetes/test-infra/blob/b5246a13a917f003450af87d15a94ff2dbc711f1/prow/crier/controller.go#L254-L258

File: prow/gerrit/adapter/adapter.go (hunk 2 above)
Comment (adshmh) [reply prow/gerrit/adapter/adapter.go]: Thank you for the review. Fixed.

File: prow/gerrit/adapter/adapter_test.go (hunk 3 above)
Comment (adshmh) [reply prow/gerrit/adapter/adapter_test.go]: Thank you for the review. Fixed.

File: prow/gerrit/adapter/adapter_test.go (hunk 4 above)
Comment (adshmh) [reply prow/gerrit/adapter/adapter_test.go]: Thank you for the reviews. Fixed.
