### PR TITLE
Fix milestone plugin comment formatting.

### LINKED ISSUE #7130: Milestone plugin comment is improperly formatted.
https://github.com/kubernetes/kubernetes/issues/60765#issuecomment-370307962

/area mungegithub
/assign @cjwagner

### PR DESCRIPTION
**Pull request by cjwagner**
fixes #7130 
The list is now sorted and uses bullets instead of a numbered list. The `/milestone clear` command is  listed separately at the end instead of suggesting that `clear` is a valid milestone.

The comment should now look like:
> @cjwagner: The provided milestone is not valid for this repository. Milestones in this repository:
> - next-candidate
> - v1.10
> - v1.11
> - v1.4
> - v1.5
> - v1.6
> - v1.7
> - v1.8
> - v1.9
>
> Use `/milestone clear` to clear the milestone.
> 
> <details>
> 
> In response to [this](https://github.com/kubernetes/test-infra/pull/947#issuecomment-262693732):
> 
> >/milestone foo
> 
> 
> Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
> </details>

/cc @krzyzacy @grodrigues3

### CODE REVIEW

**Comment by krzyzacy** [comment]
seems the version need to be sorted like
```
v1.11
v1.10
v1.9
v1.8
...
```

File: prow/plugins/milestone/milestone.go [hunk 1]
```diff
@@ -125,12 +126,17 @@ func handle(gc githubClient, log *logrus.Entry, e *github.GenericCommentEvent, m
...
 	milestoneNumber, ok := milestoneMap[proposedMilestone]
 	if !ok {
-		var buffer bytes.Buffer
-		buffer.WriteString("\t 1." + clearKeyword + "\n")
+		slice := make([]string, 0, len(milestoneMap))
 		for k := range milestoneMap {
-			buffer.WriteString("\t 1." + k + "\n")
+			slice = append(slice, k)
+		}
+		sort.Strings(slice)
```
Comment (BenTheElder) [inline prow/plugins/milestone/milestone.go]: we should probably comparison func that is aware of semantic versions

Comment (BenTheElder) [reply prow/plugins/milestone/milestone.go]: OTOH that would not be great for repos using some other milestone format. /shrug

Comment (cjwagner) [reply prow/plugins/milestone/milestone.go]: > OTOH that would not be great for repos using some other milestone format.

Yeah, I was trying to avoid making this specific to our milestone naming conventions. I don't think the sort ordering is a big deal. This comment only appears if an invalid milestone is supplied and is just meant to show all the available options so I think this sorting is probably ok?

**Comment by krzyzacy** [comment]
question here: why comments like https://github.com/kubernetes/kubernetes/pull/60872#issuecomment-371027199 fails? assume this PR will only change the commenting format.

**Comment by BenTheElder** [comment]
Side note: maybe we should use a list of milestones instead of one per line. EG in a list like `foo`, `bar` ... the existing comments eat a *lot* of screen space.

**Comment by cjwagner** [comment]
> question here: why comments like kubernetes/kubernetes#60872 (comment) fails? assume this PR will only change the commenting format.

Yeah that appears to be a regexp bug. I added a unit test based on the webhook payload for that comment and the regexp group captures the milestone as "v1.10\r". I'll fix that bug in this PR.

File: prow/plugins/milestone/milestone.go (hunk 1 above)
Comment (ixdy) [reply prow/plugins/milestone/milestone.go]: sorting versions: still one of the hardest problems in computer science. :)

**Comment by cjwagner** [comment]
I fixed the regexp bug and changed the comment format to list the available milestones in one line instead of a long bulleted list.

File: prow/plugins/milestone/milestone.go [hunk 2]
```diff
@@ -33,9 +34,9 @@ import (
 const pluginName = "milestone"
 
 var (
-	milestoneRegex   = regexp.MustCompile(`(?m)^/milestone\s+(.+)$`)
+	milestoneRegex   = regexp.MustCompile(`(?m)^/milestone\s+(.+?)\s*$`)
 	mustBeSigLead    = "You must be a member of the [%s](https://github.com/orgs/%s/teams/%s/members) github team to set the milestone."
-	invalidMilestone = "The provided milestone is not valid for this repository.  Here are the available milestones:\n %s"
+	invalidMilestone = "The provided milestone is not valid for this repository. Milestones in this repository: [%s]\n\nUse `/milestone %s` to clear the milestone."
 	clearKeyword     = "clear"
```
Comment (BenTheElder) [inline prow/plugins/milestone/milestone.go]: unrelated to this PR, but shouldn't these strings be const?

Comment (cjwagner) [reply prow/plugins/milestone/milestone.go]: Yes they should be.
/shrug
