### PR TITLE
Fix velodrome lint errors, fixes #8355

### LINKED ISSUE #8355: Fix velodrome lint errors
/good-first-issue

Run https://github.com/golang/lint on `./velodrome/...`

### PR DESCRIPTION
**Pull request by matthyx**

### CODE REVIEW

File: velodrome/transform/plugins/comment_counter.go [hunk 1]
```diff
@@ -23,17 +23,20 @@ import (
 	"k8s.io/test-infra/velodrome/sql"
 )
 
+// CommentCounterPlugin counts comments
```
Comment (fejta) [inline velodrome/transform/plugins/comment_counter.go]: 😆

Comment (matthyx) [reply velodrome/transform/plugins/comment_counter.go]: Yeah...
