### PR TITLE
Don't mix approvers and reviewers in blunderbuss

### LINKED ISSUE #16793: prow should recommend relevant approvers
**What happened**: Prow suggested a root approver for review when the PR had a single file covered by leaf approvers that did not include the root approver.

The PR only touches this file `config/testgrids/conformance/conformance-all.yaml `

With `config/testgrids/conformance/OWNERS` existing with the following contents:
```
# See the OWNERS docs at https://go.k8s.io/owners

approvers:
- spiffxp
- timothysc
```

The raw comment posted by Prow is:
```
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/kubernetes/test-infra/pull/16292#" title="Author self-approved">lubinsz</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **bentheelder**
You can assign the PR to them by writing `/assign @bentheelder` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=kubernetes%2Ftest-infra).

<details open>
Needs approval from an approver in each of these files:

- **[config/testgrids/conformance/OWNERS](https://github.com/kubernetes/test-infra/blob/master/config/testgrids/conformance/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["bentheelder"]} -->
```

https://github.com/kubernetes/test-infra/pull/16292#issuecomment-593761410

There's no reason I should be suggested here.

**What you expected to happen**:

Since `config/testgrids/conformance/OWNERS` has existing approvers, is the only directory in need of approval, and the comment is about getting **approval**, the approvers from this file should be suggested. I am not one of them, so I should not be suggested.

**How to reproduce it (as minimally and precisely as possible)**: 

Wait for prow to make suggestions for approval on a PR.

**Please provide links to example occurrences, if any**:

https://github.com/kubernetes/test-infra/pull/16292#issuecomment-593761410

**Anything else we need to know?**:

This behavior leads to excessive assignment of root approvers, we should be spreading workload to leaf owners.

cc @cjwagner 
/area prow

### PR DESCRIPTION
**Pull request by matthyx**
Relates to #16793
Avoid using `sets.String` when keeping the order matters.

### CODE REVIEW

File: prow/plugins/blunderbuss/blunderbuss.go [hunk 1]
```diff
@@ -251,6 +257,7 @@ func handle(ghc githubClient, roc repoownersClient, log *logrus.Entry, reviewerC
 func getReviewers(rc reviewersClient, ghc githubClient, log *logrus.Entry, author string, files []github.PullRequestChange, minReviewers int, useStatusAvailability bool) ([]string, []string, error) {
 	authorSet := sets.NewString(github.NormLogin(author))
 	reviewers := sets.NewString()
+	reviewersList := []string{}
```
Comment (fejta) [inline prow/plugins/blunderbuss/blunderbuss.go:260]: `var reviewersList []string` (reviewersList = append(reviewersList, "foo") works just fine)

On the other hand I don't think we need any of the changes in `getReviewers()` -- it is just a clone of reviewers

File: prow/plugins/blunderbuss/blunderbuss.go [hunk 2]
```diff
@@ -222,10 +222,16 @@ func handle(ghc githubClient, roc repoownersClient, log *logrus.Entry, reviewerC
 				if err != nil {
 					return err
 				}
+				added := 0
```
Comment (fejta) [inline prow/plugins/blunderbuss/blunderbuss.go:225]: `var added int` since you're not initializing anything

https://dave.cheney.net/practical-go/presentations/qcon-china.html#_use_a_consistent_declaration_style

File: prow/plugins/blunderbuss/blunderbuss.go [hunk 3]
```diff
@@ -289,11 +302,14 @@ func getReviewers(rc reviewersClient, ghc githubClient, log *logrus.Entry, autho
...
-				reviewers.Insert(r)
+				if !reviewers.Has(r) {
+					reviewersList = append(reviewersList, r)
+					reviewers.Insert(r)
+				}
 			}
 		}
 	}
-	return reviewers.List(), requiredReviewers.List(), nil
+	return reviewersList, requiredReviewers.List(), nil
```
Comment (fejta) [inline prow/plugins/blunderbuss/blunderbuss.go:312]: This seems like an unnecessary (and worse) change from the existing code

Comment (matthyx) [reply prow/plugins/blunderbuss/blunderbuss.go:312]: Sorry Erick but this is actually what makes this fix working... because the various loops fill reviewers in a specific order, from the leaf first up to the root.
By using the `sets.String` we are losing this information and then when we truncate the list to `maxReviewerCount` Ben goes first...

Comment (matthyx) [reply prow/plugins/blunderbuss/blunderbuss.go:312]: I have decided to keep the `reviewers` set, because it is used in all the logic with unions and co.

Comment (fejta) [reply prow/plugins/blunderbuss/blunderbuss.go:312]: Why do we depend on the order? This seems very wrong.

Comment (matthyx) [reply prow/plugins/blunderbuss/blunderbuss.go:312]: Because the list of reviewers is constructed this way to give priority to leaf approvers when there's a need to shorten the list.
You can revert that line and see how the new test fails in suggesting Ben...

**Comment by spiffxp** [comment]
/hold
Please drop the "fixes" from the description, this doesn't actually fix #16793 (ref: https://github.com/kubernetes/test-infra/issues/16793#issuecomment-631231564)

File: prow/plugins/blunderbuss/blunderbuss.go [hunk 4]
```diff
@@ -272,14 +279,20 @@ func getReviewers(rc reviewersClient, ghc githubClient, log *logrus.Entry, autho
...
 		leafReviewers = leafReviewers.Union(fileUnusedLeafs)
 		if r := findReviewer(ghc, log, useStatusAvailability, &busyReviewers, &fileUnusedLeafs); r != "" {
-			reviewers.Insert(r)
+			if !reviewers.Has(r) {
+				reviewersList = append(reviewersList, r)
+				reviewers.Insert(r)
+			}
 		}
 	}
 	// now ensure that we request review from at least minReviewers reviewers. Favor leaf reviewers.
```
Comment (matthyx) [inline prow/plugins/blunderbuss/blunderbuss.go:288]: @fejta see here it even says it will favor leaf reviewers...

File: prow/plugins/blunderbuss/blunderbuss.go [hunk 5]
```diff
@@ -289,11 +302,14 @@ func getReviewers(rc reviewersClient, ghc githubClient, log *logrus.Entry, autho
 		fileReviewers := rc.Reviewers(file.Filename).Difference(authorSet)
```
Comment (matthyx) [inline prow/plugins/blunderbuss/blunderbuss.go:302]: And the break just above ensures we only add non-leaf reviewers when we're missing some...

File: prow/plugins/blunderbuss/blunderbuss.go (hunk 3 above)
Comment (matthyx) [reply prow/plugins/blunderbuss/blunderbuss.go:312]: @fejta how would you do it?

**Comment by matthyx** [comment]
@fejta here you go

File: prow/plugins/blunderbuss/blunderbuss.go (hunk 3 above)
Comment (fejta) [reply prow/plugins/blunderbuss/blunderbuss.go]: Ordering the string seems like it will prefer Ben to Erick, when we want each person in a given owners file assigned at roughly the same frequency.

I would use a stack of sets, one per level.

AKA if the file is:

`alpha/beta/omega/something/OWNERS`

and there are 

`alpha/OWNERS`, `alpha/beta/OWNERS` and `alpha/beta/omega/something/OWNERS`

I would represent this as: `[]sets.String`

I would choose someone by something along the lines of:

```
for i := range options {
  all := options[len(options)-i] // start from leaf/OWNERS not /OWNERS
  rand.Shuffle(all, func(i,j int) { all[j], all[i] = all[i], all[j] })
  for _, choice := range all {
    if chosen.Contains(choice) {
      continue
    }
    if enoughChoices(chosen) { break/return/whatever }
  }
  log.Warn("too few choices, oh well")
}
```

File: prow/plugins/blunderbuss/blunderbuss.go (hunk 4 above)
Comment (fejta) [reply prow/plugins/blunderbuss/blunderbuss.go]: Yes we should favor leaf reviewers, but we shouldn't prioritize inside the leafs reviewers

File: prow/plugins/blunderbuss/blunderbuss.go [hunk 6]
```diff
@@ -222,10 +222,16 @@ func handle(ghc githubClient, roc repoownersClient, log *logrus.Entry, reviewerC
...
 					return err
 				}
+				var added int
 				combinedReviewers := sets.NewString(reviewers...)
-				combinedReviewers.Insert(approvers...)
-				log.Infof("Added %d approvers as reviewers. %d/%d reviewers found.", combinedReviewers.Len()-len(reviewers), combinedReviewers.Len(), *reviewerCount)
-				reviewers = combinedReviewers.List()
+				for _, approver := range approvers {
+					if !combinedReviewers.Has(approver) {
+						reviewers = append(reviewers, approver)
```
Comment (fejta) [inline prow/plugins/blunderbuss/blunderbuss.go:229]: Given that the code below does `reviewers = reviewers[:maxReviewers]`  we cannot simply range through approvers and append to this list. There is no randomization happening here, and we need that.

File: prow/plugins/blunderbuss/blunderbuss.go (hunk 3 above)
Comment (matthyx) [reply prow/plugins/blunderbuss/blunderbuss.go]: Ok, thanks for having taken the time to look deeply into it. I will implement that during the rainy weekend...

File: prow/plugins/blunderbuss/blunderbuss.go (hunk 6 above)
Comment (matthyx) [reply prow/plugins/blunderbuss/blunderbuss.go:229]: indeed, and avoid mixing them when doing so

Comment (matthyx) [reply prow/plugins/blunderbuss/blunderbuss.go:229]: now getReviewers returns a randomized list of approvers/reviewers, but keeping the leaf preference

File: prow/plugins/blunderbuss/blunderbuss.go (hunk 4 above)
Comment (matthyx) [reply prow/plugins/blunderbuss/blunderbuss.go:286]: randomization is now done just before return
