### PR TITLE
Avoid panic on invalid URI in clone_uri override

### LINKED ISSUE #29400: Setting clone_uri to use ssh causes clonerefs to panic if it has github app credentials
**What happened**:

I am switching over to using the GitHub app credentials for cloning the repository instead of configuring an SSH Key as this is simpler to maintain in theory.  Since I was using ssh to clone the repo before, I had ssh keys and clone_uri configured for the repository.  It appears that this causes a fatal error in clonerefs:

```
runtime error: invalid memory address or nil pointer dereference\n[signal
          SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1324597]\n\ngoroutine
          31 [running]:\nk8s.io/test-infra/prow/pod-utils/clone.gitCtxForRefs({{0xc00041f230,
          0xb}, {0xc00041f240, 0xd}, {0xc0001567e0, 0x2c}, {0xc00041f250, 0x6}, {0xc000156810,
          0x28}, ...}, ...)\n\tk8s.io/test-infra/prow/pod-utils/clone/clone.go:181
          +0x357\nk8s.io/test-infra/prow/pod-utils/clone.Run({{0xc00041f230, 0xb},
          {0xc00041f240, 0xd}, {0xc0001567e0, 0x2c}, {0xc00041f250, 0x6}, {0xc000156810,
          0x28}, ...}, ...)\n\tk8s.io/test-infra/prow/pod-utils/clone/clone.go:104
          +0x634\nk8s.io/test-infra/prow/clonerefs.(*Options).createRecords.func3()\n\tk8s.io/test-infra/prow/clonerefs/run.go:141
          +0x28f\ncreated by k8s.io/test-infra/prow/clonerefs.(*Options).createRecords\n\tk8s.io/test-infra/prow/clonerefs/run.go:138
          +0xf9e\n
```

The relevant code is like this:

```
	if refs.RepoLink != "" {
		repoURI = fmt.Sprintf("%s.git", refs.RepoLink)
	} else {
		repoURI = fmt.Sprintf("https://github.com/%s/%s.git", refs.Org, refs.Repo)
	}

	g := gitCtx{
		cloneDir:      PathForRefs(baseDir, refs),
		env:           env,
		repositoryURI: repoURI,
	}
	if refs.CloneURI != "" {
		g.repositoryURI = refs.CloneURI
	}

	if token != "" {
		u, _ := url.Parse(g.repositoryURI)
		if user != "" {
			u.User = url.UserPassword(user, token) // <---- CRASH HERE
		} else {
			// GitHub requires that the personal access token is set as a username.
			// e.g., https://<token>:x-oauth-basic@github.com/owner/repo.git
			u.User = url.UserPassword(token, "x-oauth-basic")
		}
		g.repositoryURI = u.String()
	}
```

My guess is that `url.Parse` failed when it was provided a URL in the form `git@github.com:owner/repo` instead of `https://githuib.com/....` but there is no error checking here, resulting in the panic instead of a graceful failure.

**What you expected to happen**:

Instead of panicking it should report a clearer error, or possibly handle this case gracefully (e.g. just leave the URL alone).

**How to reproduce it (as minimally and precisely as possible)**:

Set `clone_uri` to a `git@github.com:owner/repo` URL and also configure github app credentials in the decoration config entries.

**Please provide links to example occurrences, if any**:

Unfortunately this happened in a private repo

### PR DESCRIPTION
**Pull request by dobesv**
When clone_uri was set to an ssh URL and there were also github app credentials configured, clonerefs would panic when it failed to parse the URI but still tried to inject github app token into it anyway.

Fixes #29400

### CODE REVIEW

File: prow/pod-utils/clone/clone.go [hunk 1]
```diff
@@ -176,15 +176,18 @@ func gitCtxForRefs(refs prowapi.Refs, baseDir string, env []string, user, token
...
-		u, _ := url.Parse(g.repositoryURI)
-		if user != "" {
-			u.User = url.UserPassword(user, token)
-		} else {
-			// GitHub requires that the personal access token is set as a username.
-			// e.g., https://<token>:x-oauth-basic@github.com/owner/repo.git
-			u.User = url.UserPassword(token, "x-oauth-basic")
+		u, err := url.Parse(g.repositoryURI)
+		// Ignore invalid URL from a CloneURI override (e.g. git@github.com:owner/repo)
+		if err == nil {
```
Comment (droslean) [inline prow/pod-utils/clone/clone.go:181]: Can we also log the error for debugging purposes?

**Review by droslean — APPROVED** [review]
