### PR TITLE
prow: fix GHE pagination

### LINKED ISSUE #17776: Prow: pagination does not work on Github enterprise
**What happened**:
Hook and other Prow components do not work on Github enterprise as soon as they are used in organizations or repos with more than >100 pull requests, repos, etc.. This bug is caused by 
[`readPaginatedResultsWithValues`](https://github.com/kubernetes/test-infra/blob/master/prow/github/client.go#L1350) which doesn't handle pagination correctly for Github enterprise.

**What you expected to happen**:
That it just works :)

**How to reproduce it (as minimally and precisely as possible)**:
Run e.g. Hook with Github enterprise with a PR with more than 100 files.

**Details**:

The `readPaginatedResultsWithValues` func paginates via `next` links returned from Github. The `next` links always contain the full URL, e.g. `api.github.com/repositories/22/pulls?per_page=100&page=2`. This works as long as the base URL of Github doesn't contain a prefix. In case of Github enterprise the base  URL can look like `<ghe-url>/api/v3`. So our current code leads to calls to URLs like `<ghe-url>/api/v3/api/v3/...` 

Proposed fix: https://github.com/kubernetes/test-infra/pull/17775

### PR DESCRIPTION
**Pull request by sbueringer**
Fixes #17776

### CODE REVIEW

**Comment by sbueringer** [comment]
> Please add some tests for this

Yup, no problem. So I assume the implementation itself is okay like it is?

**Comment by sbueringer** [comment]
@alvaroaleman I added the test

File: prow/github/client_test.go [hunk 1]
```diff
@@ -795,49 +795,88 @@ func TestUnassignIssue(t *testing.T) {
...
+			func(obj interface{}) {
+				labels = append(labels, *(obj.(*[]Label))...)
+			},
+		)
+		if err != nil {
+			t.Errorf("%s: didn't expect error: %v", tc.name, err)
 		} else {
-			t.Errorf("Bad request path: %s", r.URL.Path)
+			var expectedLabels []Label
+			for _, response := range tc.responses {
```
Comment (alvaroaleman) [inline prow/github/client_test.go:873]: I am not really a fan of a test that determines its outcome at runtime (and might have bugs there) rather than having it hardcoded. I am btw also completely fine with just moving the five relevant lines here into a new function and then just testing that new functions, which is probably easier than adjusting this test.

Comment (sbueringer) [reply prow/github/client_test.go]: Makes sense. I added `expectedLabels` to the test case.

I would keep this test as table test if it's okay. I think it's easier to see this way what the actual differences between both supported variants are. It's also easier to extend in the future compared to the old test if necessary.
