### PR TITLE
Ignore delete action for label handler

### LINKED ISSUE #16579: Delete label comments may produce extra bot comments
**What happened**:

If I add a comment like `/sig abc` which does not exist. The bot will reply something like `The label(s) sig/abc cannot be applied, because the repository doesn't have them`. Then if I delete the wrong comment, the bot will reply the same message again.

**What you expected to happen**:

When I delete the wrong comment, nothing should happen.

**How to reproduce it (as minimally and precisely as possible)**:

1. comment in an issue/pr like `/sig abc`
1. delete the comment

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by gavinfish**
Fix #16579.

### CODE REVIEW

File: prow/plugins/label/label_test.go [hunk 1]
```diff
@@ -505,6 +551,29 @@ func TestLabel(t *testing.T) {
 			commenter:             orgMember,
 			expectedBotComment:    true,
 			expectedCommentText:   "The label(s) `/remove-label orchestrator/jar` cannot be applied. These labels are supported: `orchestrator/foo, orchestrator/bar`",
+			action:                github.GenericCommentActionCreated,
+		},
+		{
+			name:                  "Delete adding Labels is Case Insensitive",
```
Comment (cblecker) [inline prow/plugins/label/label_test.go]:
```suggestion
			name:                  "Don't comment when deleting label addition",
```

File: prow/plugins/label/label_test.go [hunk 2]
```diff
@@ -505,6 +551,29 @@ func TestLabel(t *testing.T) {
...
+			repoLabels:            []string{"area/infra", "priority/critical", labels.Bug},
+			issueLabels:           []string{},
+			expectedNewLabels:     []string{},
+			expectedRemovedLabels: []string{},
+			commenter:             orgMember,
+			expectedBotComment:    false,
+			action:                github.GenericCommentActionDeleted,
+		},
+		{
+			name:                  "Delete remove Committee Label",
```
Comment (cblecker) [inline prow/plugins/label/label_test.go]:
```suggestion
			name:                  "Don't comment when deleting label removal",
```
