### PR TITLE
Fix tackle ingress API incompatibility, #13492

### LINKED ISSUE #13492: Tackle Does Not Wait For a Healthy Cluster When Getting Ingresses
**What happened**:
While using tackle I tried to create a Prow cluster in my GCP project. There's a lot of pit falls but this one is a blocker. Basically a Prow cluster appears to be unable to startup without a Github bot token. After providing one the cluster pods eventually get to a healthy state but tackle advances too quickly and tries to get "ingresses" within a few seconds after submitting the token. 

```
Store your GitHub token in a file e.g. echo $TOKEN > /path/to/github/token
Input /path/to/github/token to upload into cluster: /home/c9user/token
INFO[0562] User()                                        client=github
Prow will act as jeremyje on github
Applying github token into oauth-token secret...secret/oauth-token created
Ensuring hmac secret exists at hmac-token...INFO[0563] Creating new hmac-token secret with random data... 
exists
Looking for prow's hook ingress URL... FATA[0564] Could not get ingresses                       error="the server could not find the requested resource"
```

Tackle then aborts and the workflow cannot be resumed because reattempting gives this,

```
tackle
Existing kubernetes contexts:
  0: gke_jeremyedwards-gaming-dev_us-central1-a_cloud-gaming-prow
* 1: gke_jeremyedwards-gaming-dev_us-east1-b_cloud-gaming-prow (current)
  2: gke_jeremyedwards-gaming-dev_us-east1-b_prow

Choose context or [create new]: 1
Applying admin role bindings (to create RBAC rules)...
clusterrolebinding.rbac.authorization.k8s.io/prow-admin configured
Deploying prow...
Apply starter.yaml from [github upstream]: 
Loading from https://raw.githubusercontent.com/kubernetes/test-infra/master/prow/cluster/starter.yaml
Prow is already deployed to default in gke_jeremyedwards-gaming-dev_us-east1-b_cloud-gaming-prow, overwrite? [no]: 
FATA[0010] Could not deploy prow                         error="prow already deployed"
```

**What you expected to happen**:
Tackle to setup a working Prow cluster.

**How to reproduce it (as minimally and precisely as possible)**:
Simply create a prow cluster using GKE.

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by clarketm**
This aims to resolve #13492, the following issues w/ **tackle**:
1. the ingress client returning 404:
> The Kubernetes ingress resource from the current API group `extensions.v1beta1` is moving to `networking.v1beta1` in [v1.16](https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20190125-ingress-api-group.md#116). This code change detects the server version for the currently selected context and invokes the appropriate ingress `List` resource.   
2. errant cluster overwrite behavior:
> There was a bug in the overwrite prompt where it would error when the response to the prompt was *yes* (i.e. "y", "Y" or "yes") due to overwriting the deployment configuration.

### CODE REVIEW

File: prow/cmd/tackle/ingress.go [hunk 1]
```diff
@@ -0,0 +1,81 @@
...
+WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+See the License for the specific language governing permissions and
+limitations under the License.
+*/
+
+package main
+
+import (
+	"github.com/sirupsen/logrus"
+	extensions "k8s.io/api/extensions/v1beta1"
```
Comment (fejta) [inline prow/cmd/tackle/ingress.go]: Rather than making tackle depend on all this, would it make sense to parse the output of `kubectl version`?

Comment (clarketm) [reply prow/cmd/tackle/ingress.go]: For just the version detection (i.e. [`networkingIngressAvailable`](https://github.com/kubernetes/test-infra/pull/13597/commits/85338afc7a7cb54986215359592a2de2cd9657eb#diff-b703d2541da2ba9141e53ed219959366R40)), I think that we could get away with using `kubectl version`. Conversely, for the [`toIngress`](https://github.com/kubernetes/test-infra/pull/13597/commits/85338afc7a7cb54986215359592a2de2cd9657eb#diff-b703d2541da2ba9141e53ed219959366R63) type normalization, the alternative would be duplicated code (essentially the entire [`ingress`](https://github.com/kubernetes/test-infra/pull/13597/commits/85338afc7a7cb54986215359592a2de2cd9657eb#diff-85376b10136f7ee03443261541015cf2R630) function) since the types returned by the two ingress clients ("extensions" / "networking") are different and implement different interfaces. 

My rationale was that this approach, although involving more dependencies, was the mostcanonical in that it uses the `k8s.io` packages directly. Although unlikely, it is also immune to differences in output via the `kubectl` command across versions and machines. By doing this programmatically we can leverage the strong typing of Go.

File: prow/cmd/tackle/ingress.go [hunk 2]
```diff
@@ -0,0 +1,81 @@
...
+	err := runtimeScheme.Convert(old, networkingIngress, nil)
+	if err != nil {
+		return nil, err
+	}
+
+	return networkingIngress, nil
+}
+
+// toIngress normalizes a given IngressList to the newer "networking.k8s.io/v1beta1" type.
+func toIngress(obj interface{}) (*networking.IngressList, bool) {
```
Comment (fejta) [inline prow/cmd/tackle/ingress.go]: The reflection here is unnecessary. As a general rule, stop yourself whenever you find yourself using it and figure out how to avoid it (note that the rest of the repo basically never depends on this)

You know in `ingress()` whether you have a `networking.IngressList` -- in which case call is unnecessary, or else you have an `extensions.IngressList` and definitely need to make this call, so this should be an `extensions.IngressList`, not `interface{}`

File: prow/cmd/tackle/main.go [hunk 3]
```diff
@@ -626,15 +628,27 @@ func clientConfig(context string) (*rest.Config, error) {
 }
 
 func ingress(kc *kubernetes.Clientset, ns, service string) (url.URL, error) {
+	var obj interface{}
+	var err error
```
Comment (fejta) [inline prow/cmd/tackle/main.go]: No need to declare this here

File: prow/cmd/tackle/ingress.go [hunk 4]
```diff
@@ -0,0 +1,81 @@
...
+var runtimeScheme = runtime.NewScheme()
+
+func init() {
+	extensions.AddToScheme(runtimeScheme)
+	networking.AddToScheme(runtimeScheme)
+}
+
+// networkingIngressAvailable checks if the "networking.k8s.io/v1beta1" resource is available based on Kubernetes version.
+func networkingIngressAvailable(kc kubernetes.Interface) bool {
+	serverVersion, err := kc.Discovery().ServerVersion()
```
Comment (thockin) [inline prow/cmd/tackle/ingress.go]: Why not actually check the `ServerResourcesForGroupVersion()` and look for the new type?

File: prow/cmd/tackle/main.go [hunk 5]
```diff
@@ -626,15 +628,27 @@ func clientConfig(context string) (*rest.Config, error) {
 }
 
 func ingress(kc *kubernetes.Clientset, ns, service string) (url.URL, error) {
+	var obj interface{}
```
Comment (fejta) [inline prow/cmd/tackle/main.go]: aka

```golang
var ing networking.IngressList
if networkingIngressAvail(kc) {
  ing = kc.NetworkingV1beta1().Ingresses(ns).List()
} else {
  ing = toIngress(kc.ExtensionsV1beta1().Ingresses(ns),.List())
}
```

File: prow/cmd/tackle/ingress.go (hunk 4 above)
Comment (clarketm) [reply prow/cmd/tackle/ingress.go]: 🤔 I did not realize that the `ServerResourcesForGroupVersion()` method existed. Let me see if using it is a viable option.

File: prow/cmd/tackle/ingress.go [hunk 6]
```diff
@@ -0,0 +1,81 @@
...
+	if err != nil {
+		logrus.WithError(err).Fatal("unexpected error parsing Kubernetes version")
+		return false
+	}
+
+	return version.CompareKubeAwareVersionStrings(serverVersion.String(), networkingIngressKubeVersion) <= 0
+}
+
+// fromExtensions converts a legacy "extensions/v1beta1" IngressList to the newer "networking.k8s.io/v1beta1" IngressList.
```
[the remark this answers is not in the document]
Comment (clarketm) [reply prow/cmd/tackle/ingress.go]: There may be additional helper functions that I missed in the `apimachinery` package that can perform this comparison. Additionally, @thockin made a suggestion about using `ServerResourcesForGroupVersion()` which can avoid direct version comparison. I need to investigate this further.

File: prow/cmd/tackle/ingress.go (hunk 2 above)
Comment (clarketm) [reply prow/cmd/tackle/ingress.go]: Those are my JavaScript and Python roots showing through 😉. I will clean this up to be more strict with the typing!

File: prow/cmd/tackle/ingress.go (hunk 4 above)
Comment (thockin) [reply prow/cmd/tackle/ingress.go]: I have used it before for exactly this - which "Whatever" is the best one to use...

Comment (clarketm) [reply prow/cmd/tackle/ingress.go]: Thanks, I will give it a try and update the PR.

Comment (liggitt) [reply prow/cmd/tackle/ingress.go]: https://github.com/kubernetes/kubernetes/blob/7a578febe155a7366767abce40d8a16795a96371/pkg/kubectl/cmd/util/generator.go#L212-L228 is a good example use

used like this to let `kubectl run` generate an object the server it is talking to can handle

https://github.com/kubernetes/kubernetes/blob/7a578febe155a7366767abce40d8a16795a96371/pkg/kubectl/cmd/util/generator.go#L153-L156

Comment (clarketm) [reply prow/cmd/tackle/ingress.go]: @thockin @liggitt - updated to use `ServerResourcesForGroupVersion()`

File: prow/cmd/tackle/main.go (hunk 5 above)
Comment (clarketm) [reply prow/cmd/tackle/main.go]: @fejta - updated the `toIngress(...)` function to explicitly accept an *extensions* IngressList and return a *networking* IngressList removing the type assertion.

File: prow/cmd/tackle/main.go (hunk 3 above)
Comment (fejta) [reply prow/cmd/tackle/main.go]: Move both of these inside the for loop

File: prow/cmd/tackle/ingress_test.go [hunk 7]
```diff
@@ -0,0 +1,105 @@
...
+	fakeDiscovery.Resources = append(fakeDiscovery.Resources, &fakeNetworking)
+
+	actual := networkingIngressAvailable(fakeClient)
+
+	if actual != true {
+		t.Fatalf("networkingIngressAvailable should return `true` if networking ingresses is available")
+	}
+}
+
+func TestIngressConversion(t *testing.T) {
```
Comment (fejta) [inline prow/cmd/tackle/ingress_test.go]: I do not see any useful testing happening in this method.

File: prow/cmd/tackle/ingress_test.go [hunk 8]
```diff
@@ -0,0 +1,105 @@
...
+func TestNetworkingIngressExists(t *testing.T) {
+	fakeClient := k8sFake.NewSimpleClientset()
+	fakeDiscovery := fakeClient.Discovery().(*discoveryFake.FakeDiscovery)
+	fakeNetworking := metav1.APIResourceList{
+		GroupVersion: "networking.k8s.io/v1beta1",
+		APIResources: []metav1.APIResource{{Name: "ingresses"}},
+	}
+	fakeDiscovery.Resources = append(fakeDiscovery.Resources, &fakeNetworking)
+
+	actual := networkingIngressAvailable(fakeClient)
```
Comment (fejta) [inline prow/cmd/tackle/ingress_test.go]: available seems like a better word

File: prow/cmd/tackle/ingress_test.go [hunk 9]
```diff
@@ -0,0 +1,105 @@
...
+	extensions "k8s.io/api/extensions/v1beta1"
+	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+	"k8s.io/apimachinery/pkg/util/intstr"
+	discoveryFake "k8s.io/client-go/discovery/fake"
+	k8sFake "k8s.io/client-go/kubernetes/fake"
+	"testing"
+	"time"
+)
+
+func TestNetworkingIngressNotExists(t *testing.T) {
```
Comment (fejta) [inline prow/cmd/tackle/ingress_test.go]: I'd be inclined to combine these two tests into a single table driven test (like the rest of our repo tends to do)

https://github.com/kubernetes/community/blob/master/contributors/guide/coding-conventions.md#testing-conventions

File: prow/cmd/tackle/ingress.go [hunk 10]
```diff
@@ -0,0 +1,66 @@
...
+			return true
+		}
+	}
+
+	return false
+}
+
+// toNewIngress converts a legacy "extensions/v1beta1" IngressList to the newer "networking.k8s.io/v1beta1" IngressList.
+func toNewIngress(old *extensions.IngressList) (*networking.IngressList, error) {
+	new := &networking.IngressList{}
```
Comment (fejta) [inline prow/cmd/tackle/ingress.go]: Should be written like this:
```golang
var foo networking.IngressList
err := runtimeScheme.Convert(old, &new, nil)
```

File: prow/cmd/tackle/ingress.go [hunk 11]
```diff
@@ -0,0 +1,66 @@
...
+
+	err := runtimeScheme.Convert(old, new, nil)
```
Comment (fejta) [inline prow/cmd/tackle/ingress.go]: Should be
```golang
if err := runtimeScheme.Convert(old, new, nil); err != nil {
  return err
}
```
or alterntavely
```golang
err := runtimeScheme.Convert(old, new, nil)
return new, err
```

File: prow/cmd/tackle/ingress.go [hunk 12]
```diff
@@ -0,0 +1,66 @@
...
+)
+
+var runtimeScheme = runtime.NewScheme()
+
+func init() {
+	extensions.AddToScheme(runtimeScheme)
+	networking.AddToScheme(runtimeScheme)
+}
+
+// networkingIngressAvailable checks if the "networking.k8s.io/v1beta1" resource is available based on Kubernetes version.
```
Comment (fejta) [inline prow/cmd/tackle/ingress.go]: Not entirely convinced any of these 1-3 line functions need to exist (they are only called by one function).

Not entirely convinced this file needs to exist

Comment (clarketm) [reply prow/cmd/tackle/ingress.go]: > Not entirely convinced any of these 1-3 line functions need to exist (they are only called by one function).

I do not have a problem killing the function since it may be overkill for a single expression.

> Not entirely convinced this file needs to exist

Are you not convinced because you feel the logic to do this should already be available in `apimachinery` or because you prefer this to be in [`main.go`](https://github.com/kubernetes/test-infra/pull/13597/files#diff-85376b10136f7ee03443261541015cf2)

File: prow/cmd/tackle/ingress_test.go (hunk 7 above)
Comment (clarketm) [reply prow/cmd/tackle/ingress_test.go]: I am verifying `toNewIngress` does not fail to convert and that the two different serialized lists are byte-equivalent.
