### PR TITLE
[exporter] Expose Job runtime as prometheus histograms

### LINKED ISSUE #14672: Expose prowjob metrics in a promhttp like fashion
**What would you like to be added**:

Collect prowjob metrics like it is done with promhttp for REST applications to allow visualizing things like `job x failed y times and ran on avg 30 minutes until it failed`.

I suppose https://github.com/kubernetes/test-infra/tree/master/prow/cmd/exporter would be a good fit for these metrics.

**Why is this needed**:

This can help to identify issues:

 * how long are jobs pending? (e.g. new projects were on-boarded and they let other projects unintentionally starve)
 * identifying unusual long runs on jobs (can be hints for various issues in the cluster)
 * does a job very often fail at the same time? (can be a hint for various issues in the cluster)

and so on.

### PR DESCRIPTION
**Pull request by rmohr**
Create histograms which track the time between the jobs state transitions. The histogram is pre-configured with buckets. Starting from 30 seconds, up to 10 hours: `30s, 1m, 2m, 5m, 10m, 30m, 1h, 2h, 3h, 4h, 5h, 6h, 7h, 8h, 9h, 10h`.

A resulting histogram for jobs which go from `last_state="pending"` to `state="success"` looks like this:

```
prow_job_runtime_seconds_bucket{base_ref="master",instance="exporter-9d5794677-th4vb",job="exporter",job_name="check-prow-config",job_namespace="kubevirt-prow-jobs",last_state="pending",org="kubevirt",repo="project-infra",state="success",type="presubmit",le="30"} 0
prow_job_runtime_seconds_bucket{base_ref="master",instance="exporter-9d5794677-th4vb",job="exporter",job_name="check-prow-config",job_namespace="kubevirt-prow-jobs",last_state="pending",org="kubevirt",repo="project-infra",state="success",type="presubmit",le="60"} 0
prow_job_runtime_seconds_bucket{base_ref="master",instance="exporter-9d5794677-th4vb",job="exporter",job_name="check-prow-config",job_namespace="kubevirt-prow-jobs",last_state="pending",org="kubevirt",repo="project-infra",state="success",type="presubmit",le="120"} 1
prow_job_runtime_seconds_bucket{base_ref="master",instance="exporter-9d5794677-th4vb",job="exporter",job_name="check-prow-config",job_namespace="kubevirt-prow-jobs",last_state="pending",org="kubevirt",repo="project-infra",state="success",type="presubmit",le="300"} 1
prow_job_runtime_seconds_bucket{base_ref="master",instance="exporter-9d5794677-th4vb",job="exporter",job_name="check-prow-config",job_namespace="kubevirt-prow-jobs",last_state="pending",org="kubevirt",repo="project-infra",state="success",type="presubmit",le="600"} 1
prow_job_runtime_seconds_bucket{base_ref="master",instance="exporter-9d5794677-th4vb",job="exporter",job_name="check-prow-config",job_namespace="kubevirt-prow-jobs",last_state="pending",org="kubevirt",repo="project-infra",state="success",type="presubmit",le="1800"} 1
prow_job_runtime_seconds_bucket{base_ref="master",instance="exporter-9d5794677-th4vb",job="exporter",job_name="check-prow-config",job_namespace="kubevirt-prow-jobs",last_state="pending",org="kubevirt",repo="project-infra",state="success",type="presubmit",le="3600"} 1
prow_job_runtime_seconds_bucket{base_ref="master",instance="exporter-9d5794677-th4vb",job="exporter",job_name="check-prow-config",job_namespace="kubevirt-prow-jobs",last_state="pending",org="kubevirt",repo="project-infra",state="success",type="presubmit",le="7200"} 1
prow_job_runtime_seconds_bucket{base_ref="master",instance="exporter-9d5794677-th4vb",job="exporter",job_name="check-prow-config",job_namespace="kubevirt-prow-jobs",last_state="pending",org="kubevirt",repo="project-infra",state="success",type="presubmit",le="10800"} 1
prow_job_runtime_seconds_bucket{base_ref="master",instance="exporter-9d5794677-th4vb",job="exporter",job_name="check-prow-config",job_namespace="kubevirt-prow-jobs",last_state="pending",org="kubevirt",repo="project-infra",state="success",type="presubmit",le="14400"} 1
prow_job_runtime_seconds_bucket{base_ref="master",instance="exporter-9d5794677-th4vb",job="exporter",job_name="check-prow-config",job_namespace="kubevirt-prow-jobs",last_state="pending",org="kubevirt",repo="project-infra",state="success",type="presubmit",le="18000"} 1
prow_job_runtime_seconds_bucket{base_ref="master",instance="exporter-9d5794677-th4vb",job="exporter",job_name="check-prow-config",job_namespace="kubevirt-prow-jobs",last_state="pending",org="kubevirt",repo="project-infra",state="success",type="presubmit",le="21600"} 1
prow_job_runtime_seconds_bucket{base_ref="master",instance="exporter-9d5794677-th4vb",job="exporter",job_name="check-prow-config",job_namespace="kubevirt-prow-jobs",last_state="pending",org="kubevirt",repo="project-infra",state="success",type="presubmit",le="25200"} 1
prow_job_runtime_seconds_bucket{base_ref="master",instance="exporter-9d5794677-th4vb",job="exporter",job_name="check-prow-config",job_namespace="kubevirt-prow-jobs",last_state="pending",org="kubevirt",repo="project-infra",state="success",type="presubmit",le="28800"} 1
prow_job_runtime_seconds_bucket{base_ref="master",instance="exporter-9d5794677-th4vb",job="exporter",job_name="check-prow-config",job_namespace="kubevirt-prow-jobs",last_state="pending",org="kubevirt",repo="project-infra",state="success",type="presubmit",le="32400"} 1
prow_job_runtime_seconds_bucket{base_ref="master",instance="exporter-9d5794677-th4vb",job="exporter",job_name="check-prow-config",job_namespace="kubevirt-prow-jobs",last_state="pending",org="kubevirt",repo="project-infra",state="success",type="presubmit",le="36000"} 1
prow_job_runtime_seconds_bucket{base_ref="master",instance="exporter-9d5794677-th4vb",job="exporter",job_name="check-prow-config",job_namespace="kubevirt-prow-jobs",last_state="pending",org="kubevirt",repo="project-infra",state="success",type="presubmit",le="+Inf"} 1
prow_job_runtime_seconds_sum{base_ref="master",instance="exporter-9d5794677-th4vb",job="exporter",job_name="check-prow-config",job_namespace="kubevirt-prow-jobs",last_state="pending",org="kubevirt",repo="project-infra",state="success",type="presubmit"} 60.108394254
```

In order to properly capture the metrics, the ProwJobStatus was extended with an additional timestamp:

```golang
	// PendingTime is the timestamp for when the job moved from triggered to pending
	PendingTime *metav1.Time `json:"pendingTime,omitempty"`
```

This timestamp makes sense on every agent, thus the `exporter` can export the state metrics for any agent.

Fixes #14672

### CODE REVIEW

File: prow/cmd/exporter/collector.go [hunk 1]
```diff
@@ -169,3 +171,153 @@ func sanitizeLabelName(s string) string {
...
+				state:    newJob.Status.State,
+				observed: now,
+			}
+			return
+		} else if oldJob == nil || oldJob.Status.State == newJob.Status.State {
+			// we can't determine the time when the job entered the current state, do nothing
+			// TODO: we can reconstruct some states by looking at the pods
+			return
+		}
+		// first time we see a state transition for a job live, or the job is still pending, now we record the time
```
Comment (rmohr) [inline prow/cmd/exporter/collector.go]: should have been "or the job is `triggered`" instead of `pending`.

File: prow/cmd/exporter/collector.go [hunk 2]
```diff
@@ -169,3 +171,153 @@ func sanitizeLabelName(s string) string {
...
+				// the prowjob's repo
+				"repo",
+				// the base_ref of the prowjob's repo
+				"base_ref",
+			},
+		),
+	}
+	informer.AddEventHandler(cache.ResourceEventHandlerFuncs{
+		AddFunc: func(job interface{}) {
+			lifecycleCollector.Update(nil, job.(*prowapi.ProwJob))
```
Comment (alvaroaleman) [inline prow/cmd/exporter/collector.go]: Not sure if this is an issue, but the current architecture means that we process completely synchronously: https://github.com/kubernetes/kubernetes/blob/2d8b8703de920bafaf0b893582e18e5bdd03c51d/staging/src/k8s.io/client-go/tools/cache/shared_informer.go#L652

Has the advantage that we don't need locking on the map thought.

File: prow/cmd/exporter/collector.go [hunk 3]
```diff
@@ -169,3 +171,153 @@ func sanitizeLabelName(s string) string {
 func escapeString(v string) string {
 	return escapeWithDoubleQuote.Replace(v)
 }
+
+type prowJobLifecycleCollector struct {
+	lastKnownState map[types.UID]lastState
```
Comment (alvaroaleman) [inline prow/cmd/exporter/collector.go]: I think we need some kind of garbage collection for this, else the exporter can not run too long before getting oom killed. Maybe just something that removes all jobs from this that don't exist anymore?

File: prow/cmd/exporter/collector.go [hunk 4]
```diff
@@ -169,3 +171,153 @@ func sanitizeLabelName(s string) string {
...
+	}
+}
+
+// NewProwJobLifecycleCollector creates histograms which can track the timespan between ProwJob state transitions.
+// The histograms are based on the job name, the old job state and the new job state.
+// Data is collected by hooking itself into the prowjob informer.
+// The collector will never record the same state transition twice, even if reboots happen.
+// The collector will not record the first state transition it sees after booting, and therefore miss the first transition of each job after a restart.
+// TODO: by looking at the created pods we can collect more transitions on restarts
+func NewProwJobLifecycleCollector(informer cache.SharedIndexInformer) *prowJobLifecycleCollector {
```
Comment (alvaroaleman) [inline prow/cmd/exporter/collector.go]: In order to keep this a bit more tidy, can we put the `ProwJobLifecycleCollector` into its own package?

File: prow/cmd/exporter/collector.go [hunk 5]
```diff
@@ -169,3 +171,153 @@ func sanitizeLabelName(s string) string {
...
+}
+
+type lastState struct {
+	state    prowapi.ProwJobState
+	observed time.Time
+}
+
+func (pjc *prowJobLifecycleCollector) Update(oldJob *prowapi.ProwJob, newJob *prowapi.ProwJob) {
+	now := time.Now()
+	if lastKnownState, exists := pjc.lastKnownState[newJob.UID]; !exists {
```
Comment (alvaroaleman) [inline prow/cmd/exporter/collector.go]: Maybe I am missing something here, but wouldn't it be sufficient to:
* if !exist: Insert unconditionally into map, return
* if newState == oldState: return
* Update map entry, create metric?

File: prow/cmd/exporter/collector.go [hunk 6]
```diff
@@ -169,3 +171,153 @@ func sanitizeLabelName(s string) string {
...
+		if newJob.Status.State == prowapi.TriggeredState {
+			now = newJob.CreationTimestamp.Time
```
[the remark this answers is not in the document]
Comment (rmohr) [reply prow/cmd/exporter/collector.go]: This is an optimization, to be able to pick up transitions from triggered to pending for jobs which are in the "triggered" state and the exporter just started. If I don't do this, I have no idea when a job, which is still in triggered state, first entered that state and I would not be able to measure the timespan before it enters pending.

File: prow/cmd/exporter/collector.go (hunk 2 above)
Comment (rmohr) [reply prow/cmd/exporter/collector.go]: I think that the operations in `Update` are lightweight enough to do it here already, and in contrast  to controllers we need to catch the actual transitions. If we think it is too heavy-weight, I could push the jobs into a channel with a buffer.

File: prow/cmd/exporter/collector.go (hunk 3 above)
Comment (rmohr) [reply prow/cmd/exporter/collector.go]: This is garbage-collected. See the `Delete` callback. It worst it still requires less space than the informer cache of the jobs.

I am more concerned regarding to the historams themselves. Over time we will have more and more histograms, which probably means that we push obsolete histograms and need more and more memory. I am not yet entirely sure on how to best handle it.

File: prow/cmd/exporter/collector.go (hunk 4 above)
Comment (rmohr) [reply prow/cmd/exporter/collector.go]: Yes

File: prow/cmd/exporter/collector.go (hunk 5 above)
Comment (rmohr) [reply prow/cmd/exporter/collector.go]: I think it is necessary, to correctly detect transitions. I think that I could detect the `triggered` to `pending` transition a little bit more elegant.

**Comment by rmohr** [comment]
> `prow_job_execution_time_seconds` that is the actual job duration based on the pod later?

I am not sure. Maybe I should in this PR already start adding a pod informer. I find `pending` not very useful if it is combining scheduling and running.

File: prow/cmd/exporter/collector.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (stevekuznetsov) [reply prow/cmd/exporter/collector.go]: We should record this in `ProwJob.Status` as a new field, set by `plank` etc

File: prow/cmd/exporter/collector.go [hunk 7]
```diff
@@ -169,3 +171,153 @@ func sanitizeLabelName(s string) string {
 func escapeString(v string) string {
 	return escapeWithDoubleQuote.Replace(v)
 }
+
+type prowJobLifecycleCollector struct {
```
Comment (stevekuznetsov) [inline prow/cmd/exporter/collector.go]: We should have fields in spec for this, I don't like holding state here

File: prow/cmd/exporter/collector.go (hunk 1 above)
Comment (stevekuznetsov) [reply prow/cmd/exporter/collector.go]: Triggered is not even a phase today, we should make it one

File: prow/cmd/exporter/collector.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (rmohr) [reply prow/cmd/exporter/collector.go]: @stevekuznetsov  Do you have a structure in mind for all the timestamps?

Right now there is 

```
  completionTime: 2019-10-10T07:08:29Z # we enter failed/succeeded
  startTime: 2019-10-10T06:34:23Z # same like creation time
```

Maybe something like this?

```
  scheduledTime:  # in pending state where the pod is scheduled, to indicate the actual runtime
  schedulingTime: # from trigger to pending
```

**Comment by rmohr** [comment]
> What's the worry on "many histograms"? Shouldn't we just have a histogram per state?

I would say it is ok to have many, and we want them so that we can investigate sub-states and aggregate them, but if the exporter runs for a very long time, it would report hundreds of hobs which may not even exist anymore for months. Not sure if it is an issue.

File: prow/cmd/exporter/collector.go (hunk 1 above)
Comment (rmohr) [reply prow/cmd/exporter/collector.go]: Hm, as far as I know it is. Every job which I see created is initially in `triggered`.

**Comment by rmohr** [comment]
> Shouldn't we just have a histogram per state?

@stevekuznetsov @alvaroaleman I wonder if we need the `last_state`. I am not that familiar enough with the statemachine details of prow. Could we loose information, if we don't have the `last_state` as a label? E.g. can a triggered job directly go to `failure`?

**Comment by rmohr** [comment]
Tests are now there.

@alvaroaleman @stevekuznetsov are we ok with having the follwoing timestamps on the spec:

```
  completionTime: 2019-10-10T07:08:29Z # exists already, we enter failed/succeeded
  startTime: 2019-10-10T06:34:23Z # exists already, same like creation time
  scheduledTime:  # in pending state where the pod is scheduled, to record the execution time
  schedulingTime: # from trigger to pending
```

**Comment by alvaroaleman** [comment]
> @alvaroaleman @stevekuznetsov are we ok with having the follwoing timestamps on the spec:
>  completionTime: 2019-10-10T07:08:29Z # exists already, we enter failed/succeeded
  startTime: 2019-10-10T06:34:23Z # exists already, same like creation time
  scheduledTime:  # in pending state where the pod is scheduled, to record the execution time
  schedulingTime: # from trigger to pending

hmm, I think we have to be very careful in how we name these things because otherwise this will get super confusing.

So in your suggestion the `schedulingTime` is basically the time Prow needs from Job creation till "agent creates execution unit" (Per default Plank creating a pod) but not the time that execution unit (the pod per default) is waiting to get scheduled, right?

I personally would tend to not introduce any new names for existing phases here and just name the durations after the phase. What we currently don't have and probably want is the actual "executionTime" of the job, as the `pending` time includes scheduling and potentially recreation after eviction.

Interestingly enough the `executionTime` is displayed in the spyglass GCS view, presumably spyglass just substracts the timestamp from the `started.json` from the one in `finished.json´ to get this info? It doesn't seem to be anywhere on the prowjob

**Comment by rmohr** [comment]
> hmm, I think we have to be very careful in how we name these things because otherwise this will get super confusing.

@alvaroaleman yep. Came now up with a different set. See the PR description.

File: prow/apis/prowjobs/v1/types.go [hunk 8]
```diff
@@ -532,7 +532,22 @@ func (g *GCSConfiguration) Validate() error {
 
 // ProwJobStatus provides runtime metadata, such as when it finished, whether it is running, etc.
 type ProwJobStatus struct {
-	StartTime      metav1.Time  `json:"startTime,omitempty"`
+	StartTime metav1.Time `json:"startTime,omitempty"`
+	// PreviousPodCreateTime holds the creation time of the pod which was previously
+	// created for the job and unexpectedly disappeared
+	PreviousPodCreateTime *metav1.Time `json:"PreviousPodCreateTime,omitempty"`
```
Comment (alvaroaleman) [inline prow/apis/prowjobs/v1/types.go]: I don't think we can create properties that reference pods, because depending on the `agent` there may be no pod. Maybe we can instead use a `[]Condition` that has a free-text `name` field and a `duration` field?

Comment (rmohr) [reply prow/apis/prowjobs/v1/types.go]: I can see why this would not work for a pipeline, but for instance plank also stores the pod name itself also in the spec, so just checking the agent might be good enough?

Another option would be to let directly plank create the metrics. Then they would not be needed on the spec, and plank has access to the pod.

**Comment by rmohr** [comment]
@alvaroaleman as discussed offline, removed all timestamps, except `PendingTime` again. This new timestamp allows exporting the same metrics for every agent.

Since the rest of the timestamps are specific to the default agent, I would let `plank` in a followup itself export the agent specific histograms.

File: prow/metrics/prowjobs/collector.go [hunk 9]
```diff
@@ -0,0 +1,172 @@
...
+
+type prowJobLifecycleCollector struct {
+	HistogramVec *prometheus.HistogramVec
+}
+
+func (pjc *prowJobLifecycleCollector) Update(oldJob *prowapi.ProwJob, newJob *prowapi.ProwJob) {
+	if oldJob == nil {
+		return
+	}
+	if oldJob.Status.State != newJob.Status.State {
```
Comment (alvaroaleman) [inline prow/metrics/prowjobs/collector.go]: Thats definitely a very nitpicky comment, but generally its nice to keep the happy path left-aligned and avoid arrow code, i.E. instead of putting everything inside the `oldJob.Status.State != newJob.Status.State `, do a if `oldJob.Status.State == newJob.Status.State { return } `

File: prow/metrics/prowjobs/collector_test.go [hunk 10]
```diff
@@ -0,0 +1,191 @@
...
+					},
+					Status: prowapi.ProwJobStatus{
+						CompletionTime: &defaultCompleteTime,
+						PendingTime:    &defaultPendingTime,
+					},
+				},
+			}, expected: expected{
+				collected: nil,
+			}},
+		{name: "should collect job transitions for trasitions from %s to  %s",
```
Comment (stevekuznetsov) [inline prow/metrics/prowjobs/collector_test.go]: we misspell `transitions` a number of different ways in this file

File: prow/plank/controller.go [hunk 11]
```diff
@@ -517,6 +519,7 @@ func (c *Controller) syncTriggeredJob(pj prowapi.ProwJob, pm map[string]coreapi.
 	}
 
 	if pj.Status.State == prowapi.TriggeredState {
+		pj.Status.PendingTime = &pod.CreationTimestamp
```
Comment (stevekuznetsov) [inline prow/plank/controller.go]: I expected to see unit tests updated for `plank` to reflect this

File: prow/metrics/prowjobs/collector.go [hunk 12]
```diff
@@ -0,0 +1,172 @@
...
+				(4 * time.Hour).Seconds(),
+				(5 * time.Hour).Seconds(),
+				(6 * time.Hour).Seconds(),
+				(7 * time.Hour).Seconds(),
+				(8 * time.Hour).Seconds(),
+				(9 * time.Hour).Seconds(),
+				(10 * time.Hour).Seconds(),
+			},
+		},
+		[]string{
```
Comment (stevekuznetsov) [inline prow/metrics/prowjobs/collector.go]: So I still don't really understand the worry about "the number of histograms". Based on the labels we have listed here, we have bounded cardinality. You don't create a histogram per job execution (one run of a job) but for all executions of a job across time.

File: prow/metrics/prowjobs/collector.go [hunk 13]
```diff
@@ -0,0 +1,172 @@
...
+	"github.com/prometheus/client_golang/prometheus"
+	"github.com/sirupsen/logrus"
+	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+
+	"k8s.io/client-go/tools/cache"
+
+	prowapi "k8s.io/test-infra/prow/apis/prowjobs/v1"
+)
+
+type prowJobLifecycleCollector struct {
```
Comment (stevekuznetsov) [inline prow/metrics/prowjobs/collector.go]: Why do we need this structure? Just


```go
var (
    lifecycleHistograms = prometheus.NewHistogramVec(...
```

File: prow/metrics/prowjobs/collector.go [hunk 14]
```diff
@@ -0,0 +1,172 @@
...
+	informer.AddEventHandler(cache.ResourceEventHandlerFuncs{
+		UpdateFunc: func(oldJob, newJob interface{}) {
+			lifecycleCollector.Update(oldJob.(*prowapi.ProwJob), newJob.(*prowapi.ProwJob))
+		},
+	})
+	return lifecycleCollector
+}
+
+func getJobLabel(oldJob *prowapi.ProwJob, newJob *prowapi.ProwJob) jobLabel {
+	jl := jobLabel{jobNamespace: newJob.Namespace, jobName: newJob.Spec.Job, jobType: string(newJob.Spec.Type), state: string(newJob.Status.State), last_state: string(oldJob.Status.State)}
```
Comment (stevekuznetsov) [inline prow/metrics/prowjobs/collector.go]: nit: can you put these on separate lines, so it's not one single long one

File: prow/metrics/prowjobs/collector.go [hunk 15]
```diff
@@ -0,0 +1,172 @@
...
+
+	if newJob.Spec.Refs != nil {
```
Comment (stevekuznetsov) [inline prow/metrics/prowjobs/collector.go]: use the primary ref getter func for this

File: prow/metrics/prowjobs/collector.go [hunk 16]
```diff
@@ -0,0 +1,172 @@
...
+	if oldJob.Status.State != newJob.Status.State {
+
+		labels := getJobLabel(oldJob, newJob)
+		histogram, err := pjc.HistogramVec.GetMetricWithLabelValues(labels.values()...)
+		if err != nil {
+			logrus.WithError(err).Error("Failed to get a histogram for a prowjob")
+			return
+		}
+
+		var oldTime metav1.Time
```
Comment (stevekuznetsov) [inline prow/metrics/prowjobs/collector.go]: nit: you could simplify this logic by storing the pointers


```go
var oldTime, newTime *metav1.Time

switch oldJob.Status.State {
case prowapi.TriggeredState:
    oldTime = &oldJob.CreationTimestamp
case prowapi.PendingState:
    oldTime = oldJob.PendingTimestamp
}
switch newJob.Status.State {
case prowapi.FailureState, prowapi.SuccessState, prowapi.ErrorState, prowapi.AbortedState:
    oldTime = newJob.CompletionTimestamp
case prowapi.PendingState:
    oldTime = newJob.PendingTimestamp
}
if oldTime == nil || newTime == nil {
    return
}
```

File: prow/cmd/exporter/main.go [hunk 17]
```diff
@@ -54,16 +55,13 @@ func (o *options) Validate() error {
 	return o.kubernetes.Validate(false)
 }
 
-func mustRegister(component string, lister lister) *prometheus.Registry {
```
Comment (stevekuznetsov) [inline prow/cmd/exporter/main.go]: Wait so what happened to the original intent of this method? Why did you remove it?

File: prow/plank/controller.go [hunk 18]
```diff
@@ -535,27 +538,27 @@ func (c *Controller) syncTriggeredJob(pj prowapi.ProwJob, pm map[string]coreapi.
 
 // TODO: No need to return the pod name since we already have the
```
[the remark this answers is not in the document]
Comment (rmohr) [reply prow/plank/controller.go]: In case we have an error on the ProwJob update, we loose the time. I don't think it matters too much, but taking the creation time sounds more accurate, since it can be re-discovered on retries.

[the remark this answers is not in the document]
Comment (rmohr) [reply prow/plank/controller.go]: Change to use `now()`.

File: prow/metrics/prowjobs/collector_test.go (hunk 10 above)
Comment (rmohr) [reply prow/metrics/prowjobs/collector_test.go]: Fixed.

File: prow/plank/controller.go (hunk 11 above)
Comment (rmohr) [reply prow/plank/controller.go]: Done.

File: prow/metrics/prowjobs/collector.go (hunk 12 above)
Comment (rmohr) [reply prow/metrics/prowjobs/collector.go]: Yes, my only worry would be the size of the document which prometheus scrapes. Since the exporter does not stop to export timers ever, it could become a very expensive scrape targets.

File: prow/metrics/prowjobs/collector.go (hunk 13 above)
Comment (rmohr) [reply prow/metrics/prowjobs/collector.go]: Removed

File: prow/metrics/prowjobs/collector.go (hunk 14 above)
Comment (rmohr) [reply prow/metrics/prowjobs/collector.go]: Done

File: prow/metrics/prowjobs/collector.go (hunk 16 above)
Comment (rmohr) [reply prow/metrics/prowjobs/collector.go]: Done.

File: prow/cmd/exporter/main.go (hunk 17 above)
Comment (rmohr) [reply prow/cmd/exporter/main.go]: If the original idea was to not export the metrics of the exporter to the push-gateway then it was fine. The `registry` parameter which you can pass to the `push` function is only exposed at `/metrics` and not pushed. I re-wrote it do look like it does in the other components. There the go instrumentation is already registered via `init`.

**Comment by rmohr** [comment]
@stevekuznetsov @alvaroaleman should be ready for another round. Thanks!

File: prow/metrics/prowjobs/collector.go (hunk 15 above)
Comment (rmohr) [reply prow/metrics/prowjobs/collector.go]: @stevekuznetsov I could not find the getter. I only found a few places where it is done like in this function. Could you point me to the getter?

File: prow/metrics/prowjobs/collector.go (hunk 9 above)
Comment (rmohr) [reply prow/metrics/prowjobs/collector.go]: Done.

File: prow/apis/prowjobs/v1/types.go [hunk 19]
```diff
@@ -532,7 +532,10 @@ func (g *GCSConfiguration) Validate() error {
 
 // ProwJobStatus provides runtime metadata, such as when it finished, whether it is running, etc.
 type ProwJobStatus struct {
-	StartTime      metav1.Time  `json:"startTime,omitempty"`
+	StartTime metav1.Time `json:"startTime,omitempty"`
```
Comment (stevekuznetsov) [inline prow/apis/prowjobs/v1/types.go]: nit: could we add godoc here, is `StartTime` ever different from `ProwJob.Metadata.CreationTimestamp`?

File: prow/cmd/exporter/main.go (hunk 17 above)
Comment (stevekuznetsov) [reply prow/cmd/exporter/main.go]: The intent was to create a registry and expose that via a handler in the server for metrics. You've removed that and always pass `nil`. Why? The label metrics are complex, let's revert this change unless you run this component in your cluster and can verify at runtime that `prow_job_labels` and `prow_job_annotations` work as expected.

Comment (stevekuznetsov) [reply prow/cmd/exporter/main.go]: Feel free to register the new histograms using the native client methods in an `init()`

File: prow/metrics/prowjobs/collector.go (hunk 15 above)
Comment (stevekuznetsov) [reply prow/metrics/prowjobs/collector.go]: Ah, we have `MainRefs()` but for the downward API .. nevermind

File: prow/cmd/exporter/main.go (hunk 17 above)
Comment (stevekuznetsov) [reply prow/cmd/exporter/main.go]: Let's change absolutely nothing about the way they are handled. They are circumventing the canonical Go client usecase on purpose.

Comment (rmohr) [reply prow/cmd/exporter/main.go]: Ack, Changed.

File: prow/apis/prowjobs/v1/types.go (hunk 19 above)
Comment (rmohr) [reply prow/apis/prowjobs/v1/types.go]: Done.

**Comment by rmohr** [comment]
/hold

verifying

**Comment by rmohr** [comment]
/hold cancel

@stevekuznetsov now it should be good: doing `histogramVec.GetMetricWithLabelValues` now only if we really have the timstamps, to avoid creating empty histograms.

Could you have a final look again? Thanks.

File: prow/metrics/prowjobs/collector.go [hunk 20]
```diff
@@ -0,0 +1,172 @@
...
+	}
+
+	var oldTime *metav1.Time
+	var newTime *metav1.Time
+
+	switch oldJob.Status.State {
+	case prowapi.TriggeredState:
+		oldTime = &oldJob.CreationTimestamp
+	case prowapi.PendingState:
+		if oldJob.Status.PendingTime == nil {
```
Comment (stevekuznetsov) [inline prow/metrics/prowjobs/collector.go]: I still think it would be way clearer to just do this check once ... do both of the `switch` statements, then if either is `nil`, return. That way we don't seven different places we need to `return`

Comment (rmohr) [reply prow/metrics/prowjobs/collector.go]: ok, let me look into that.

Comment (stevekuznetsov) [reply prow/metrics/prowjobs/collector.go]: Example was here https://github.com/kubernetes/test-infra/pull/14695#discussion_r334089698

Comment (rmohr) [reply prow/metrics/prowjobs/collector.go]: and you were definitely right. Done.

Comment (rmohr) [reply prow/metrics/prowjobs/collector.go]: > Example was here [#14695 (comment)](https://github.com/kubernetes/test-infra/pull/14695#discussion_r334089698)

Yes, sorry missed it.
