### PR TITLE
Deck: Wait for cache sync

### LINKED ISSUE #15480: Deck attempts to update job list before cache starts
/kind oncall-hotlist
/area prow
/area prow/deck
/assign @alvaroaleman @Katharine @michelle192837 

```yaml
{
 insertId: "12upppwg6kxylbg"  
 jsonPayload: {
  component: "deck"   
  error: "the cache is not started, can not read objects"   
  file: "prow/deck/jobs/jobs.go:190"   
  func: "k8s.io/test-infra/prow/deck/jobs.(*JobAgent).tryUpdate"   
  level: "warning"   
  msg: "Error updating job list."   
 }
 labels: {…}  
 logName: "projects/oss-prow/logs/deck"  
 receiveTimestamp: "2019-12-04T23:09:59.527164080Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2019-12-04T23:09:44Z"  
}
```

Can we please cleanup race?

### PR DESCRIPTION
**Pull request by alvaroaleman**
This PR makes Deck wait for its caches to be synced before proceeding with starting up.

Fixes #15480

/assign @fejta @clarketm

### CODE REVIEW

File: prow/cmd/deck/main.go [hunk 1]
```diff
@@ -546,6 +546,11 @@ func prodOnlyMain(cfg config.Getter, pluginAgent *plugins.ConfigAgent, o options
 			logrus.Info("Manager stopped gracefully.")
 		}
 	}()
+	mgrSyncCtx, mgrSyncCtxCancel := context.WithTimeout(context.Background(), 30*time.Second)
+	defer mgrSyncCtxCancel()
```
Comment (stevekuznetsov) [inline prow/cmd/deck/main.go]: Please use the interrupt defer so that cleanup tasks can still use the client if they need to @alvaroaleman

Comment (alvaroaleman) [reply prow/cmd/deck/main.go]: This contexts sole purpose is to give a timeout for the syncing and its being closed so we do not leak goroutines. The `defer` was just the lazy version of `call it regardless of sync success`.

If this doesn't work, the client can't be used anyways.
