### PR TITLE
Fix race conditions in submit-queue tests.

### LINKED ISSUE #3639: Data race in mungegithub
```
cd mungegithub/mungers
go test -race
```
```
==================
WARNING: DATA RACE
Write at 0x00c42040ce70 by goroutine 86:
  k8s.io/test-infra/mungegithub/mungers.TestSubmitQueue.func1()
      /home/spxtr/go/src/k8s.io/test-infra/mungegithub/mungers/submit-queue_test.go:905 +0x1dd
  net/http.HandlerFunc.ServeHTTP()
      /home/spxtr/bin/go/src/net/http/server.go:1942 +0x51
  net/http.(*ServeMux).ServeHTTP()
      /home/spxtr/bin/go/src/net/http/server.go:2238 +0xa2
  net/http.serverHandler.ServeHTTP()
      /home/spxtr/bin/go/src/net/http/server.go:2568 +0xbc
  net/http.(*conn).serve()
      /home/spxtr/bin/go/src/net/http/server.go:1825 +0x71a

Previous write at 0x00c42040ce70 by goroutine 70:
  k8s.io/test-infra/mungegithub/mungers.TestSubmitQueue.func1()
      /home/spxtr/go/src/k8s.io/test-infra/mungegithub/mungers/submit-queue_test.go:905 +0x1dd
  net/http.HandlerFunc.ServeHTTP()
      /home/spxtr/bin/go/src/net/http/server.go:1942 +0x51
  net/http.(*ServeMux).ServeHTTP()
      /home/spxtr/bin/go/src/net/http/server.go:2238 +0xa2
  net/http.serverHandler.ServeHTTP()
      /home/spxtr/bin/go/src/net/http/server.go:2568 +0xbc
  net/http.(*conn).serve()
      /home/spxtr/bin/go/src/net/http/server.go:1825 +0x71a

Goroutine 86 (running) created at:
  net/http.(*Server).Serve()
      /home/spxtr/bin/go/src/net/http/server.go:2668 +0x35f
  net/http/httptest.(*Server).goServe.func1()
      /home/spxtr/bin/go/src/net/http/httptest/server.go:235 +0xa2

Goroutine 70 (running) created at:
  net/http.(*Server).Serve()
      /home/spxtr/bin/go/src/net/http/server.go:2668 +0x35f
  net/http/httptest.(*Server).goServe.func1()
      /home/spxtr/bin/go/src/net/http/httptest/server.go:235 +0xa2
==================
```
and others

### PR DESCRIPTION
**Pull request by cjwagner**
Fix two data races in submit-queue tests

fixes #3639 
/cc @spxtr

### CODE REVIEW

File: mungegithub/mungers/submit-queue_test.go [hunk 1]
```diff
@@ -902,6 +904,8 @@ func TestSubmitQueue(t *testing.T) {
 				// so we don't want to modify the PR there. Instead we need
 				// to wait until the second time we check Jenkins, which happens
 				// we did the IsMerged() check.
+				testChecksLock.Lock()
+				defer testChecksLock.Unlock()
```
Comment (spxtr) [inline mungegithub/mungers/submit-queue_test.go]: I think defers happen when the function returns, not when the loop continues. Is this what you intend?

Comment (cjwagner) [inline mungegithub/mungers/submit-queue_test.go]: This is inside a handler function definition. The lock is not locked or unlocked inside the loop, instead handlers are registered inside the loop. The lock is used when the handler is called and the defer is activated when the handler returns.

**Comment by spxtr** [comment]
OK
/lgtm
/test all
