### PR TITLE
Fix prow.k8s.io/build-id Pod label

### LINKED ISSUE #17612: prow.k8s.io/build-id Pod label is always the empty string.
**What happened**:
It looks like the `prow.k8s.io/build-id` label is always set to the empty string on ProwJob pods.
```
$ kubectl get po -n test-pods -oyaml | grep "prow.k8s.io/build-id" | sort | uniq
      prow.k8s.io/build-id: ""
```
**What you expected to happen**:
Pods should be properly labelled with their build IDs.

/area prow
/area prow/plank

### PR DESCRIPTION
**Pull request by adshmh**
Closes #17612

### CODE REVIEW

File: prow/pod-utils/decorate/podspec.go [hunk 1]
```diff
@@ -152,18 +152,19 @@ func LabelsAndAnnotationsForJob(pj prowapi.ProwJob) (map[string]string, map[stri
 }
 
 // ProwJobToPod converts a ProwJob to a Pod that will run the tests.
-func ProwJobToPod(pj prowapi.ProwJob, buildID string) (*coreapi.Pod, error) {
-	return ProwJobToPodLocal(pj, buildID, "")
+func ProwJobToPod(pj prowapi.ProwJob) (*coreapi.Pod, error) {
```
Comment (cjwagner) [inline prow/pod-utils/decorate/podspec.go:155]: Why was this function signature changed? The build ID should always be available when creating a pod for a ProwJob and including it in the function signature makes the requirement explicit.

File: prow/plank/controller.go [hunk 2]
```diff
@@ -524,41 +516,39 @@ func (c *Controller) syncTriggeredJob(pj prowapi.ProwJob, pm map[string]corev1.P
...
 func (c *Controller) getBuildID(name string) (string, error) {
 	return pjutil.GetBuildID(name, c.totURL)
 }
 
 func getPodBuildID(pod *corev1.Pod) string {
-	for _, env := range pod.Spec.Containers[0].Env {
-		if env.Name == "BUILD_ID" {
-			return env.Value
-		}
+	if buildID, ok := pod.ObjectMeta.Labels[kube.ProwBuildIDLabel]; ok {
```
Comment (cjwagner) [inline prow/plank/controller.go:550]: Since we've been failing to set this label, this won't work for existing jobs. We should ensure backwards compatibility.

File: prow/pod-utils/decorate/podspec.go (hunk 1 above)
Comment (adshmh) [reply prow/pod-utils/decorate/podspec.go]: Thank you for the review. Fixed.

File: prow/plank/controller.go (hunk 2 above)
Comment (adshmh) [reply prow/plank/controller.go]: Thank you for the review. Fixed and added unit tests to cover.

File: prow/plank/controller.go [hunk 3]
```diff
@@ -524,42 +516,49 @@ func (c *Controller) syncTriggeredJob(pj prowapi.ProwJob, pm map[string]corev1.P
...
+	pj.Status.PodName = pod.ObjectMeta.Name
+	return nil
 }
 
 func (c *Controller) getBuildID(name string) (string, error) {
 	return pjutil.GetBuildID(name, c.totURL)
 }
 
 func getPodBuildID(pod *corev1.Pod) string {
+	if buildID, ok := pod.ObjectMeta.Labels[kube.ProwBuildIDLabel]; ok && buildID != "" {
```
Comment (cjwagner) [inline prow/plank/controller.go:551]: super nit: This is slightly more idiomatic:
```go
if buildID := pod.ObjectMeta.Labels[kube.ProwBuildIDLabel]; buildID != "" {
```

Comment (adshmh) [reply prow/plank/controller.go:551]: Thank you for the review. Tide merged the PR before I could correct it.

Comment (cjwagner) [reply prow/plank/controller.go:551]: Yeah, I didn't want to block the PR on this since it is such a minor style change. It's just a small tip for the future.
