### PR TITLE
prow/github/report: modify the test failure reporting logic

### LINKED ISSUE #1723: Less e-mail spam from e2e test failures
At the moment if a PR doesn't build or has some other major problem it will fail all of the e2e tests. The bot will create a new comment for every single failure. That new comment will have the summarization of all test failures for the commit, but it still creates a new comment and deletes the old. This means I get ~8 emails. Even though the github history looks good.

Personally I'd rather get 1 e-mail for each pull that failed. And have that first comment edited with all the info. If a new push is bad the first failure should create a new comment (delete any old comments) and will generate an e-mail. If a following test fails the bot should update that comment rather than create new/delete.

Doing so would cut way down on e-mail spam. Admittedly it would lose some e-mail fidelity as you wouldn't get all test failures in your e-mail, only the first. But it seems like a good tradeoff to me.

1 email per push.

### PR DESCRIPTION
**Pull request by neolit123**
on test failures:
- edit old comments instead of deleting them.
- create new comments when a new job commit SHA is found.
- only show the job commit SHA above the table and not for every entry.

also:
- skip updating comments when a ProwJob is for an old commit.
- split a couple of loop processors out of parseIssueComments()
- add unit tests.

/area prow
/kind feature
/assign @krzyzacy @fejta 
fixes #1723

/hold

untested in a real prow deployment - i was hoping we have a staging repo?

### CODE REVIEW

File: prow/github/report/report.go [hunk 1]
```diff
@@ -156,7 +159,16 @@ func Report(ghc GithubClient, reportTemplate *template.Template, pj prowapi.Prow
 	if len(refs.Pulls) == 0 {
 		return nil
 	}
-
+	icomm, err := ghc.ListPRCommits(refs.Org, refs.Repo, refs.Pulls[0].Number)
```
Comment (krzyzacy) [inline prow/github/report/report.go]: ^^ there's already a `ListIssueComments` below which does the same thing :-)

Comment (neolit123) [reply prow/github/report/report.go]: hm, but `ListIssueComments` is for comments? i use this call (to `ListPRCommits`) to get the commits for a PR job at the time when this job reaches `Report()`.

File: prow/github/report/report.go [hunk 2]
```diff
@@ -156,7 +159,16 @@ func Report(ghc GithubClient, reportTemplate *template.Template, pj prowapi.Prow
...
+	if err != nil {
+		return fmt.Errorf("error listing commits: %v", err)
+	}
+	// Check if the ProwJob SHA exists in the list of PR commit SHAs.
+	// If it doesn't, skip reporting as this is an old ProwJob.
+	sha := pj.Spec.Refs.Pulls[0].SHA
+	if !findSHAInPRCommits(sha, icomm) {
```
Comment (neolit123) [inline prow/github/report/report.go]: this logic needs a minor change.

it has to also handle the case where a commit exists in the list of commits in a PR, but this commit is not the latest.
in such a case skip too.

File: prow/github/report/report.go [hunk 3]
```diff
@@ -215,8 +240,20 @@ func parseIssueComments(pj prowapi.ProwJob, botName string, ics []github.IssueCo
 			previousComments = append(previousComments, latestComment)
 		}
 		latestComment = ic.ID
+		// Split the issue comment to obtain the list of SHAs written at the end of the comment
+		// after commentTag. tagSplit[1] cannot fail as we already know ic.Body contains the tag.
+		tagSplit := strings.Split(ic.Body, commentTag)
```
Comment (fejta) [inline prow/github/report/report.go]: This doesn't seem necessary, we can just `for _, line := range strings.Split(ic.Body, "\n") { ... }`, right?

AKA the exact location of the commit in this comment doesn't seem particularly important.

File: prow/github/report/report.go [hunk 4]
```diff
@@ -198,6 +221,8 @@ func parseIssueComments(pj prowapi.ProwJob, botName string, ics []github.IssueCo
 	var previousComments []int
 	var latestComment int
 	var entries []string
+	pullSHA := pj.Spec.Refs.Pulls[0].SHA
+	newSHA := true
 	// First accumulate result entries and comment IDs
 	for _, ic := range ics {
 		if ic.User.Login != botName {
```
Comment (fejta) [inline prow/github/report/report.go]: Please delete the TODO(spxtr) code on L206

File: prow/github/report/report.go (hunk 2 above)
Comment (fejta) [reply prow/github/report/report.go]: https://github.com/kubernetes/test-infra/blob/6f40a71acfc801ca4c1f4a314f2293398487f576/prow/github/client.go#L2426

File: prow/github/report/report.go (hunk 1 above)
Comment (krzyzacy) [reply prow/github/report/report.go]: 🤦‍♂️ sorry, I read it as `ListPRComments` and got confused

File: prow/github/report/report.go [hunk 5]
```diff
@@ -250,13 +287,11 @@ func parseIssueComments(pj prowapi.ProwJob, botName string, ics []github.IssueCo
 			newEntries = append(newEntries, entries[i])
```
Comment (fejta) [inline prow/github/report/report.go]: Part of the intent here should be that if:
* jobs A B C reported for commit X,
* I push commit Y,
* when job B finishes for commit Y, create a table with just B's failure, not A and C (since these results are for the wrong commit).

File: prow/github/report/report.go [hunk 6]
```diff
@@ -189,6 +201,17 @@ func Report(ghc GithubClient, reportTemplate *template.Template, pj prowapi.Prow
...
+	for _, c := range icomm {
+		if c.SHA != sha {
+			continue
+		}
+		return true
+	}
+	return false
+}
+
 // parseIssueComments returns a list of comments to delete, a list of table
```
Comment (fejta) [inline prow/github/report/report.go]: I would be nice to break apart this function a bit into pieces we can unit test better. these for loops are hard to understand

File: prow/github/report/report.go (hunk 2 above)
Comment (neolit123) [reply prow/github/report/report.go]: just spoke to @BenTheElder about this during the kind meeting. he reminded me that this is by author date. so the handling won't be ideal and we have to rely on what the user pushes chronologically.

Comment (BenTheElder) [reply prow/github/report/report.go]: at least, I'm pretty sure most of the APIs are by author date, @cjwagner is the expert 😅

File: prow/github/report/report.go (hunk 3 above)
Comment (neolit123) [reply prow/github/report/report.go]: hm, given now the first sentence writes the `pj.Spec.Refs.Pulls[0].SHA` commit on top of the issue comment, this means that this status report is for that particular commit and any different incoming `pj.Spec.Refs.Pulls[0].SHA` should clear comment, as long as we skip correctly old jobs in `Reptort()`. :thinking: 

which means the whole `<!-- list of SHAs at the end -->` might not be needed.
i will double check this.

File: prow/github/report/report.go (hunk 5 above)
Comment (neolit123) [reply prow/github/report/report.go]: yes, i think we are already doing this.

File: prow/github/report/report.go [hunk 7]
```diff
@@ -189,6 +200,16 @@ func Report(ghc GithubClient, reportTemplate *template.Template, pj prowapi.Prow
...
 }
 
+// commitIsLatest returns true if a given commit SHA is found
+// to be the last one in a slice of RepositoryCommits.
+func commitIsLatest(sha string, commits []github.RepositoryCommit) bool {
+	total := len(commits)
+	if total == 0 {
+		return false
+	}
+	return sha == commits[total-1].SHA
```
Comment (stevekuznetsov) [inline prow/github/report/report.go]: IIRC there is some weirdness with ordering in this API -- @cjwagner are we certain we get the commits in logical order here?

File: prow/github/report/report.go [hunk 8]
```diff
@@ -198,65 +219,37 @@ func parseIssueComments(pj prowapi.ProwJob, botName string, ics []github.IssueCo
...
 	var latestComment int
 	var entries []string
+	var newComment bool
 	// First accumulate result entries and comment IDs
 	for _, ic := range ics {
 		if ic.User.Login != botName {
 			continue
 		}
-		// Old report comments started with the context. Delete them.
-		// TODO(spxtr): Delete this check a few weeks after this merges.
```
Comment (stevekuznetsov) [inline prow/github/report/report.go]: LOL

File: prow/github/report/report.go (hunk 2 above)
Comment (neolit123) [reply prow/github/report/report.go]: so i did a quick `GET` check and the github API for `pulls/N/commits` returns the same order as the order which can be viewed on the UI. in such an order the last commit in the list seems to  always be the one being tested.

**Comment by neolit123** [comment]
PR updated.

File: prow/github/report/report.go [hunk 9]
```diff
@@ -306,3 +301,47 @@ func createComment(reportTemplate *template.Template, pj prowapi.ProwJob, entrie
 	}...)
 	return strings.Join(lines, "\n"), nil
 }
+
+// getOldEntries processes a comment body and obtains a list of entries.
+func getOldEntries(body string) []string {
```
Comment (stevekuznetsov) [inline prow/github/report/report.go]: Why not store machine-readable content hidden from users?

Comment (neolit123) [reply prow/github/report/report.go]: i'm not a fan of the flatten, unflatten but i wanted to keep this PR scoped.
it kind of already went out of scope by extracting these get*Entries functions out. :)

File: prow/github/report/report.go (hunk 7 above)
Comment (neolit123) [reply prow/github/report/report.go]: yes, also interested in this.

File: prow/github/report/report.go (hunk 9 above)
Comment (stevekuznetsov) [reply prow/github/report/report.go]: /shrug

File: prow/github/report/report.go (hunk 7 above)
Comment (neolit123) [reply prow/github/report/report.go]: /assign @cjwagner

Comment (cjwagner) [reply prow/github/report/report.go]: I don't know how the v3 API is ordered, the v4 API is the one that orders commits by author date. Since the v3 API doesn't specify an ordering I don't think we should rely on it. https://developer.github.com/v3/pulls/#list-commits-on-a-pull-request

What about fetching the PullRequest itself and comparing against the `.Head.SHA` field? That also has the benefit of not being a paginated endpoint so it will only ever cost 1 API token.

**Comment by neolit123** [comment]
@cjwagner updated to use GetPullRequest and compare against Head.SHA.

File: prow/github/report/report_test.go [hunk 10]
```diff
@@ -171,12 +146,43 @@ func TestParseIssueComment(t *testing.T) {
 			expectedContexts: []string{"foo test"},
 			expectedUpdate:   123,
 		},
+		{
+			name:    "should create new comment for new commit",
```
Comment (fejta) [inline prow/github/report/report_test.go]: Can we have this scenario include something other than `bla test` (`foo test`?) I believe previously this would result in a `foo test` result at `sha123` and `bla test` result at `sha456`. Will be nice to show that we'll now only show a table with sha123 results.

File: prow/github/report/report.go [hunk 11]
```diff
@@ -198,65 +220,37 @@ func parseIssueComments(pj prowapi.ProwJob, botName string, ics []github.IssueCo
...
-			}
-		}
-		// Use the current result if there is an old one.
-		if pj.Spec.Context == f1[0] {
-			keep = false
-		}
-		if keep {
-			newEntries = append(newEntries, entries[i])
-		}
+	if !newComment {
```
Comment (fejta) [inline prow/github/report/report.go]: I'm pretty sure this now causes it to throw out table rows for old commits, nice!

File: prow/github/report/report_test.go (hunk 10 above)
Comment (neolit123) [reply prow/github/report/report_test.go]: good catch - i've missed this case. now added as:
> should update existing comment to add failure about new job on the same commit

also slightly renamed the other similar case names.

**Comment by neolit123** [comment]
unless there are any objections we can `/hold cancel`.

also, please let me know how / when this can be tested.
not sure if there is a staging prow running on a staging repo somewhere.

**Comment by fejta** [comment]
/hold cancel

In general feel free to `/hold cancel` whenever you're satisfied and want things to merge. We tend to always /lgtm + /hold cancel so that we can give more thorough, optional feedback that the PR author can decide to accept or reject according to their interest/need.

**Comment by neolit123** [comment]
ACK, just wanted to see if there are more comments.
