### PR TITLE
Prevent release note duplicate messages

### LINKED ISSUE #16971: repeated commenting on release-note-needed when cherry pick is filed
**What happened**:

Screen Shot 2020-03-24 at 4 34 01 PM

I received emails for each of these

**What you expected to happen**:

We should make this comment once. Besides unnecessary notifications this must be costing us API tokesn

**How to reproduce it (as minimally and precisely as possible)**:

File a cherry pick PR to kubernetes/kubernetes

**Please provide links to example occurrences, if any**:

https://github.com/kubernetes/kubernetes/pull/89448
https://github.com/kubernetes/kubernetes/pull/89446

**Anything else we need to know?**:

/area prow

### PR DESCRIPTION
**Pull request by jherrera123**
Fixes #16971

**Special notes for your reviewer**:
When you open a PR, multiple plugins add labels to the PR. Each label that is added, is triggering a call to handlePR in the release note plugin, adding a new release note comment to the issue.

The way I'm fixing this issue is by limiting the label add trigger to only labels related to release note plugin.

I added unit tests, and also tested the fix on a gke prow instance connected to a github repo.

/area prow/plugins

/assign @BenTheElder

### CODE REVIEW

File: prow/plugins/releasenote/releasenote.go [hunk 1]
```diff
@@ -212,11 +212,32 @@ func handlePullRequest(pc plugins.Agent, pr github.PullRequestEvent) error {
 	return handlePR(pc.GitHubClient, pc.Logger, &pr)
 }
 
-func handlePR(gc githubClient, log *logrus.Entry, pr *github.PullRequestEvent) error {
+func shouldIgnorePR(pr *github.PullRequestEvent) bool {
```
Comment (alvaroaleman) [inline prow/plugins/releasenote/releasenote.go:215]: Nit: The fact that a `true` return means the PR will be ignored instead of having a `shouldHandlePR` makes this hard to read for me at this time

File: prow/plugins/releasenote/releasenote.go [hunk 2]
```diff
@@ -212,11 +212,32 @@ func handlePullRequest(pc plugins.Agent, pr github.PullRequestEvent) error {
...
 		pr.Action != github.PullRequestActionLabeled {
+		return true
+	}
+
+	// Ignoring unrelated PR labels prevents duplicate release note messages
+	if pr.Action == github.PullRequestActionLabeled {
+		isRNLabelAdd := false
+		for _, rnLabel := range allRNLabels {
+			if pr.Label.Name == rnLabel {
+				isRNLabelAdd = true
```
Comment (alvaroaleman) [inline prow/plugins/releasenote/releasenote.go:228]: Nit: You can just `return false` here and save the variable declaration above and the check below

File: prow/plugins/releasenote/releasenote.go (hunk 1 above)
Comment (jherrera123) [reply prow/plugins/releasenote/releasenote.go]: Method has been changed to shouldHandlePR

File: prow/plugins/releasenote/releasenote.go (hunk 2 above)
Comment (jherrera123) [reply prow/plugins/releasenote/releasenote.go]: I removed the variable and I'm returning true, since the logic was changed to shouldHandlePR
