### PR TITLE
make kubekins-test image tag base on branch names

### LINKED ISSUE #1133: wrong version of kubekins-test image being used in PR and CI
`ci-kubernetes-test-go-release-1.4` has been continuously failing since https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-test-go-release-1.4/8/, which correlates in time to when #1068 was merged.

It appears that all of the `ci-kubernetes-test-go` and `-verify` builds are using the 1.5 version of the `kubekins-test` image, whereas previously they were using version-specific versions.

As a result, verify/unit runs are now broken on everything before `release-1.5`. This is also hitting developers trying to cherry-pick to release branches, e.g. https://github.com/kubernetes/kubernetes/pull/36786#issuecomment-261689511.

We need to restore the previous behavior, possibly by looking at `git` tags to decide which image version to use.

cc @fejta @spxtr @krzyzacy @krousey

### PR DESCRIPTION
**Pull request by krzyzacy**
relies on KUBE_VERIFY_GIT_BRANCH

Fixes #1133

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/test-infra/1148)

### CODE REVIEW

File: jenkins/gotest-dockerized.sh [hunk 1]
```diff
@@ -35,6 +35,15 @@ mkdir -p "${HOST_ARTIFACTS_DIR}"
 # From _inside_ a container that has the host's docker mapped in, the $PATH
 # provided must be resolvable on the *HOST*, not the container.
 
+# default to go version 1.5 image tag
+KUBEKINS_TAG="1.5-v20161109-d9a98f2"
+
+if [[ ${KUBE_VERIFY_GIT_BRANCH} == *"1.2" ]] || \
```
Comment (ixdy) [inline jenkins/gotest-dockerized.sh]: minor nit: maybe quote the variable, like `"${KUBE_VERIFY_GIT_BRANCH}"`?

File: jenkins/gotest-dockerized.sh [hunk 2]
```diff
@@ -45,5 +54,5 @@ docker run --rm=true \
   -e "KUBE_VERIFY_GIT_BRANCH=${KUBE_VERIFY_GIT_BRANCH:-}" \
   -e "REPO_DIR=${REPO_DIR}" \
   -e "HOST_ARTIFACTS_DIR=${HOST_ARTIFACTS_DIR}" \
-  -i gcr.io/k8s-testimages/kubekins-test:1.5-v20161109-d9a98f2 \
+  -i gcr.io/k8s-testimages/kubekins-test:${KUBEKINS_TAG} \
```
Comment (ixdy) [inline jenkins/gotest-dockerized.sh]: quote here too - `"gcr.io/k8s-testimages/kubekins-test:${KUBEKINS_TAG}"`

Comment (krzyzacy) [inline jenkins/gotest-dockerized.sh]: done.

**Comment by krzyzacy** [comment]
Ack. Probably need do it when we need to have another go version.

**Comment by krzyzacy** [comment]
sudo lgtm per Jeff's approval
