### PR TITLE
Fix approval comment links to markdown files with OWNERS headers.

### LINKED ISSUE #6710: bot comments bad OWNERS file paths in kubernetes/website repo
The bot shows bad OWNERS file path in its comment:

https://github.com/kubernetes/website/pull/7224#issuecomment-362875101

Please notice the below lines. The OWNERS files path are incorrect.

```
Needs approval from an approver in each of these OWNERS Files:
docs/concepts/cluster-administration/network-plugins.md/OWNERS
docs/getting-started-guides/rkt/index.md/OWNERS
```

xref: https://github.com/kubernetes/website/issues/7289#issuecomment-363978843

/assign @fejta @cjwagner

### PR DESCRIPTION
**Pull request by cjwagner**
fixes #6710 
/cc @xiangpengzhao @fejta

### CODE REVIEW

File: prow/plugins/approve/approvers/approvers_test.go [hunk 1]
```diff
@@ -908,3 +908,48 @@ Approvers can cancel approval by writing ` + "`/approve cancel`" + ` in a commen
...
+Assign the PR to them by writing ` + "`/assign @alice @doctor`" + ` in a comment when ready.
+
+*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with ` + "`/approve no-issue`" + `
+
+The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands).
+
+The pull request process is described [here](https://git.k8s.io/community/contributors/devel/owners.md#the-code-review-process)
+
+<details open>
+Needs approval from an approver in each of these OWNERS Files:
```
Comment (xiangpengzhao) [inline prow/plugins/approve/approvers/approvers_test.go]: This line might be confusing if the below list contains `.md` files. We can make it more clear I guess.

File: prow/plugins/approve/approvers/approvers_test.go [hunk 2]
```diff
@@ -908,3 +908,48 @@ Approvers can cancel approval by writing ` + "`/approve cancel`" + ` in a commen
...
+
+- **[a/OWNERS](https://github.com/org/project/blob/master/a/OWNERS)**
+- **[b/README.md](https://github.com/org/project/blob/master/b/README.md)**
```
Comment (xiangpengzhao) [inline prow/plugins/approve/approvers/approvers_test.go]: I don't read the logic of finding owner header of `.md` files. I wonder if we still try to find the owner header of the md file and list the md file here if some md files don't have an owner header. I notice there are md files in k/website don't have such headers. @cjwagner

Comment (cjwagner) [reply prow/plugins/approve/approvers/approvers_test.go]: That isn't a concern here. `.md` files will only be reference in the `RepoOwners` struct if they were found to have valid OWNERS headers (and the headers were successfully parsed) while walking the repo to load the OWNERS info.

File: prow/plugins/approve/approvers/approvers_test.go (hunk 1 above)
Comment (cjwagner) [reply prow/plugins/approve/approvers/approvers_test.go]: Fixed.

File: prow/plugins/approve/approvers/approvers_test.go (hunk 2 above)
Comment (cjwagner) [reply prow/plugins/approve/approvers/approvers_test.go]: I modified a test to show that `.md` files without OWNERS headers work as like any other file.

File: prow/repoowners/repoowners.go [hunk 3]
```diff
@@ -279,7 +279,7 @@ func (o *RepoOwners) walkFunc(path string, info os.FileInfo, err error) error {
 
 	// '.md' files may contain assignees at the top of the file in a yaml header
 	// Note that these assignees only apply to the file itself.
-	if o.enableMDYAML && filename != ownersFileName && strings.HasSuffix(filename, "md") {
+	if o.enableMDYAML && strings.HasSuffix(filename, ".md") {
```
Comment (fejta) [inline prow/repoowners/repoowners.go]: Why do we want to support this? Use an OWNERS file.

Comment (cjwagner) [reply prow/repoowners/repoowners.go]: This is pattern is used extensively throughout the k/website repo. See this [query](https://github.com/kubernetes/website/search?utf8=%E2%9C%93&q=approvers+filename%3A*.md&type=). 
We support this pattern because OWNERS files didn't previously support per-file `approvers` and `reviewers` as is now achievable with regexp filtering. By allowing OWNERS config in markdown headers, each file can have its own `approvers` and `reviewers` without having to be put in its own folder with its own OWNERS file.
