### PR TITLE
Make tide slow down batch merges and wait for mergeability to be calculated if needed.

### LINKED ISSUE #5171: Tide fails to merge batch
Tide failed to merge a batch because the base branch was modified.
Here are the logs for the sync loop of interest and the loops preceeding and following that loop:
```
{"controller":"tide","level":"info","msg":"Building tide pool.","time":"2017-10-25T20:17:34Z"}
{"controller":"tide","level":"info","msg":"Search for query \"type:pr state:open repo:kubernetes/test-infra label:lgtm label:approved -label:needs-ok-to-test -label:do-not-merge/work-in-progress -label:do-not-merge/hold label:\"cncf-cla: yes\"\" cost 1 point(s). 4944 remaining.","time":"2017-10-25T20:17:35Z"}
{"controller":"tide","level":"info","msg":"kubernetes/test-infra master: 5 PRs, 12 PJs.","time":"2017-10-25T20:17:41Z"}
{"controller":"tide","level":"info","msg":"Passing PRs: [5168]","time":"2017-10-25T20:17:41Z"}
{"controller":"tide","level":"info","msg":"Pending PRs: []","time":"2017-10-25T20:17:41Z"}
{"controller":"tide","level":"info","msg":"Missing PRs: [5169 5147 5010 3883]","time":"2017-10-25T20:17:41Z"}
{"controller":"tide","level":"info","msg":"Passing batch: []","time":"2017-10-25T20:17:41Z"}
{"controller":"tide","level":"info","msg":"Pending batch: true","time":"2017-10-25T20:17:41Z"}
{"controller":"tide","level":"info","msg":"Action: WAIT, Targets: []","time":"2017-10-25T20:17:41Z"}
{"level":"info","msg":"Sync time: 6.118784868s","time":"2017-10-25T20:17:41Z"}
{"controller":"tide","level":"info","msg":"Building tide pool.","time":"2017-10-25T20:18:34Z"}
{"controller":"tide","level":"info","msg":"Search for query \"type:pr state:open repo:kubernetes/test-infra label:lgtm label:approved -label:needs-ok-to-test -label:do-not-merge/work-in-progress -label:do-not-merge/hold label:\"cncf-cla: yes\"\" cost 1 point(s). 4943 remaining.","time":"2017-10-25T20:18:35Z"}
{"controller":"tide","level":"info","msg":"kubernetes/test-infra master: 5 PRs, 12 PJs.","time":"2017-10-25T20:18:41Z"}
{"controller":"tide","level":"info","msg":"Passing PRs: [5168]","time":"2017-10-25T20:18:41Z"}
{"controller":"tide","level":"info","msg":"Pending PRs: []","time":"2017-10-25T20:18:41Z"}
{"controller":"tide","level":"info","msg":"Missing PRs: [5169 5147 5010 3883]","time":"2017-10-25T20:18:41Z"}
{"controller":"tide","level":"info","msg":"Passing batch: [5169 5147 5010]","time":"2017-10-25T20:18:41Z"}
{"controller":"tide","level":"info","msg":"Pending batch: false","time":"2017-10-25T20:18:41Z"}
{"controller":"tide","error":"Base branch was modified. Review and try the merge again.","level":"warning","msg":"Merge failed: PR is unmergable. How did it pass tests?!","time":"2017-10-25T20:18:43Z"}
{"controller":"tide","error":"Base branch was modified. Review and try the merge again.","level":"warning","msg":"Merge failed: PR is unmergable. How did it pass tests?!","time":"2017-10-25T20:18:43Z"}
{"controller":"tide","level":"info","msg":"Action: MERGE_BATCH, Targets: [{5169 {jlewi} {master refs/heads/} {test-infra kubernetes/test-infra {kubernetes}} {{5a29a5f4e6e83a1a35218cbcc193ccdc82ed3086}} {[{{{SUCCESS}}}]}} {5147 {marun} {master refs/heads/} {test-infra kubernetes/test-infra {kubernetes}} {{e11ff2305cb472084ec3b20f35625a5e363ff282}} {[{{{SUCCESS}}}]}} {5010 {kargakis} {master refs/heads/} {test-infra kubernetes/test-infra {kubernetes}} {{248c288ae0f0f26fe831f5a3637a8fb5953b7058}} {[{{{SUCCESS}}}]}}]","time":"2017-10-25T20:18:43Z"}
{"level":"info","msg":"Sync time: 8.281722494s","time":"2017-10-25T20:18:43Z"}
{"controller":"tide","level":"info","msg":"Building tide pool.","time":"2017-10-25T20:19:34Z"}
{"controller":"tide","level":"info","msg":"Search for query \"type:pr state:open repo:kubernetes/test-infra label:lgtm label:approved -label:needs-ok-to-test -label:do-not-merge/work-in-progress -label:do-not-merge/hold label:\"cncf-cla: yes\"\" cost 1 point(s). 4942 remaining.","time":"2017-10-25T20:19:35Z"}
{"controller":"tide","level":"info","msg":"kubernetes/test-infra master: 4 PRs, 0 PJs.","time":"2017-10-25T20:19:40Z"}
{"controller":"tide","level":"info","msg":"Passing PRs: []","time":"2017-10-25T20:19:40Z"}
{"controller":"tide","level":"info","msg":"Pending PRs: []","time":"2017-10-25T20:19:40Z"}
{"controller":"tide","level":"info","msg":"Missing PRs: [5168 5147 5010 3883]","time":"2017-10-25T20:19:40Z"}
{"controller":"tide","level":"info","msg":"Passing batch: []","time":"2017-10-25T20:19:40Z"}
{"controller":"tide","level":"info","msg":"Pending batch: false","time":"2017-10-25T20:19:40Z"}
{"controller":"tide","level":"info","msg":"Action: TRIGGER, Targets: [{5010 {kargakis} {master refs/heads/} {test-infra kubernetes/test-infra {kubernetes}} {{248c288ae0f0f26fe831f5a3637a8fb5953b7058}} {[{{{SUCCESS}}}]}}]","time":"2017-10-25T20:19:40Z"}
{"level":"info","msg":"Sync time: 5.85054185s","time":"2017-10-25T20:19:40Z"}
```

cc @spxtr 
/assign

### PR DESCRIPTION
**Pull request by cjwagner**
I didn't want to use `IsMergeable` as originally planned because it will always cost us 1 more API token per merged PR than we would have needed if we just retried the merge with a delay.

fixes #5171 
/area prow
/kind bug
/cc @stevekuznetsov @spxtr

### CODE REVIEW

File: prow/tide/tide.go [hunk 1]
```diff
@@ -448,21 +449,50 @@ func (c *Controller) pickBatch(sp subpool) ([]PullRequest, error) {
...
+				} else {
+					return err
+				}
 			} else {
-				return err
+				log.Info("Merged.")
+				// If we have more PRs to merge, sleep to give Github time to recalculate
+				// mergeability.
+				if i+1 < len(prs) {
+					time.Sleep(time.Second * 3)
```
Comment (kargakis) [inline prow/tide/tide.go]: Unless tide starts handling subpools in parallel, this will slow it down considerably when there are batches to merge across repos.

Comment (cjwagner) [reply prow/tide/tide.go]: If we merge 50 PRs in a day that is ~2.5 minutes of total delay over the whole day which shouldn't be too bad. I'll parallelize the subpool processing to minimize this though. We should be doing that anyways, the subpools don't affect each other.

Comment (kargakis) [reply prow/tide/tide.go]: > We should be doing that anyways, the subpools don't affect each other.

OTOH, one of the initial requirements for tide was the ability to synchronize merges across repos. Unclear whether that's still a design goal though. cc @spxtr

Comment (cjwagner) [reply prow/tide/tide.go]: Done. I used logic similar to the prowjob controllers.

**Comment by stevekuznetsov** [comment]
Parallelism looks good

/hold cancel

File: prow/tide/tide.go (hunk 1 above)
Comment (spxtr) [reply prow/tide/tide.go]: I still haven't heard much of a coherent proposal for how to handle the myriad of edge cases that crop up with synchronized merges across repos. Tide should be able to help, but it's not a solution in itself.
