### PR TITLE
Make Tide's set status contexts on PRs with deleted HeadRefs.

### LINKED ISSUE #6153: Tide is failing to set statuses
Tide is running into some problems setting statuses:
<ol>
<li>
Some GraphQL PullRequest objects are missing HeadRefs, while the V3 API has them. So some of the `OID` fields in the `PullRequest` structs are empty for specific PRs.
The GraphQL query: 
<pre>
{
 repository(owner:"kubernetes", name:"charts"){
   pullRequest(number:3219) { 
     headRef { target { oid } }
   }
 }
}
</pre>
Returns "pullRequest": { "headRef": null}, but on the v3 API ( https://api.github.com/repos/kubernetes/charts/pulls/3219 ), the head ref is present as expected.
@rmmh Notified Github of this issue.
</li>
<li>
Tide repeatedly updated specific commit statuses as if they had not been successfully set the previous loop. Each sync loop the following was logged:
<pre>{"client":"github","level":"info","msg":"CreateStatus(kubernetes, test-infra, c165db353a954700a695f36f70a2c1c14bdf26ce, {pending https://prow.k8s.io/tide.html Not in tide pool. tide})","time":"2018-01-04T20:50:28Z"}
{"client":"github","level":"info","msg":"CreateStatus(kubernetes, federation, adae9fe32bb0f913627893aafb79d64da7278d9d, {pending https://prow.k8s.io/tide.html Not in tide pool. tide})","time":"2018-01-04T20:50:28Z"}
{"client":"github","level":"info","msg":"CreateStatus(kubernetes, charts, 4ba0bf6220f487c8c40865020afac67dc9e576c7, {pending https://prow.k8s.io/tide.html Not in tide pool. tide})","time":"2018-01-04T20:50:28Z"}
</pre>
</li>
<li>
If Tide fails to set a single status the entire sync loop is aborted. ref #6152
</li>
</ol>
cc @spxtr

### PR DESCRIPTION
**Pull request by cjwagner**
fixes #6153 
I tested this out in dryrun with the production queries and without dryrun on a test repo.
/cc @spxtr

### CODE REVIEW

**Comment by cjwagner** [comment]
I'm not certain that (2) from #6153 has actually been fixed:

> Tide repeatedly updated specific commit statuses as if they had not been successfully set the previous loop.

I couldn't reproduce that behavior on my test repo after making these fixes. I'll watch the logs after deploying this to see if it is still occurring.

File: prow/github/client.go [hunk 1]
```diff
@@ -1271,7 +1271,8 @@ func (c *Client) GetFile(org, repo, filepath, commit string) ([]byte, error) {
 
 // Query runs a GraphQL query using shurcooL/githubql's client.
 func (c *Client) Query(ctx context.Context, q interface{}, vars map[string]interface{}) error {
-	c.log("Query", q, vars)
+	// Don't log query here because Query is typically called multiple times to get all pages.
```
Comment (spxtr) [inline prow/github/client.go]: One could argue against this change and instead suggest lowering the log level if this is too noisy. I don't mind either way.

**Comment by spxtr** [comment]
/lgtm
/hold
Bump?

File: prow/github/client.go (hunk 1 above)
Comment (cjwagner) [reply prow/github/client.go]: I was considering that as well, but I think most of the other Github client calls are worth knowing about, this one is just especially noisy because it is often called multiple times per search and doesn't format very nicely. We can change this later if desired.

**Comment by cjwagner** [comment]
Added a version bump. I'll deploy this tomorrow.

File: prow/github/client.go (hunk 1 above)
Comment (kargakis) [reply prow/github/client.go]: The rest of github api calls are running on Info. Can we move this in Debug at least?

Comment (kargakis) [reply prow/github/client.go]: Ok, if we log once per search I am fine with it.
