### PR TITLE
enforce no vendored tests in test-infra

### LINKED ISSUE #5331: bazel build failes locally
Checkout the HEAD code of test-infra, bazel build fails. It works on my former branch.

```
cloud@ubuntu:~/go/src/k8s.io/test-infra$ bazel build //...
ERROR: /home/cloud/go/src/k8s.io/test-infra/vendor/gopkg.in/yaml.v2/BUILD:24:1: no such package 'vendor/gopkg.in/check.v1': BUILD file not found on package path and referenced by '//vendor/gopkg.in/yaml.v2:go_default_xtest'.
ERROR: Analysis of target '//vendor/gopkg.in/yaml.v2:go_default_xtest' failed; build aborted: no such package 'vendor/gopkg.in/check.v1': BUILD file not found on package path.
INFO: Elapsed time: 4.287s
```

### PR DESCRIPTION
**Pull request by BenTheElder**
This makes `hack/verify-bazel.sh` and `hack/update-bazel.sh` enforce that there are no `*_test.go` files in `vendor/*`.

See also: https://github.com/bazelbuild/rules_go/issues/725, https://github.com/golang/dep/issues/944
At some point this should be solved upstream (by pretty much the same thing, but in `dep`), but until then we can make sure anyone who touches vendor runs our update script.

fixes #5331

:this_is_fine:</img>

### CODE REVIEW

File: hack/update-bazel.sh [hunk 1]
```diff
@@ -20,6 +20,9 @@ set -o pipefail
 TESTINFRA_ROOT=$(git rev-parse --show-toplevel)
 TMP_GOPATH=$(mktemp -d)
 
+# no unit tests in vendor
+find ${TESTINFRA_ROOT}/vendor/ -name "*_test.go" -delete
```
Comment (ixdy) [inline hack/update-bazel.sh]: I kinda feel like putting this in the update-bazel script is misplaced. Should we have a `go dep` wrapper instead?

Comment (cblecker) [reply hack/update-bazel.sh]: it's not exactly the clearest, but because updating bazel is required anytime you run dep (it blows away all `BUILD` files in vendor/), it's not the worst place either.

**Comment by cblecker** [comment]
/hold
Preventing merge if there's discussion

File: hack/update-bazel.sh (hunk 1 above)
Comment (BenTheElder) [reply hack/update-bazel.sh]: Maybe? `hack/update-bazel.sh` seemed like our "run after changing the build" which also fit "run after changing vendor/"

Comment (BenTheElder) [reply hack/update-bazel.sh]: We can't really enforce that anyone uses our dep wrapper as well, so we'd still need to have a `verify` somewhere.

Comment (BenTheElder) [reply hack/update-bazel.sh]: Oh hmm @cblecker your comment hadn't loaded (??), that sums up what I was thinking more concisely 🙃

Comment (krzyzacy) [reply hack/update-bazel.sh]: it works for me, as the current workflow is always
`dep ensure`
`dep prune`
`./hack/update-bazel.sh`

Or maybe we can also make use of the `hack/update-all.sh` if it should not be in `update-bazel.sh`?

**Comment by xiangpengzhao** [comment]
Also tested locally and works for me. I like the short command `bazel  build //...` I'm not sure which way to make this work is better though :)

**Comment by BenTheElder** [comment]
We could have another pair of scripts (verify-vendor and update-vendor?),
maybe roll those in to an {update,verify}-build which calls the vendor
scripts and the bazel scripts? It seemed simple to roll these into the
bazel scripts since the presubmit will remind you to run them and removing
go files will require running update-bazel though.

I think we should come up with something and go with it soonish though,
`bazel build -- //... -//vendor/..` is not a friendly welcome to our
bazel-ified repo and I don't think dep will be fixed very quickly.

**Comment by BenTheElder** [comment]
Meanwhile travis passed 5 hours ago and never updated the GitHub status ... #1342

**Comment by BenTheElder** [comment]
I just ran into this again, does anyone have any thoughts on this?

**Comment by fejta** [comment]
If we do not want vendored code to include tests, we should have a presubmit test that enforces this

**Comment by BenTheElder** [comment]
> If we do not want vendored code to include tests, we should have a presubmit test that enforces this

This PR makes the `verify-bazel` script / presubmit check that since changing vendor changes the `BUILD` and makes `update-bazel` remove them before fixing the `BUILD` (since you'd have to do those together anyhow).

**Comment by fejta** [comment]
SGTM what do you want thoughts about?

**Comment by BenTheElder** [comment]
This was previously LGTM and then `/hold`-ed for further discussion on where the fix should live, but in the meantime local test/build has been broken for test-infra. I want to either merge this or see an alternative suggested & merged.

**Comment by cblecker** [comment]
Personally, I'm fine with this living here until such time as this is wrapped into dep. Perhaps a more detailed comment on why we are doing it? Or link back to this PR?

**Comment by BenTheElder** [comment]
> Personally, I'm fine with this living here until such time as this is wrapped into dep. Perhaps a more detailed comment on why we are doing it? Or link back to this PR?

I added comments and a ref back to this PR let's
/hold cancel
And then once `dep` is fixed we can remove these.

**Comment by sdboyer** [comment]
> We could have another pair of scripts (verify-vendor and update-vendor?), and then maybe roll those in to an {update,verify}-build which calls both the vendor scripts and the bazel scripts?

just followed a little link chain back from a dep issue and saw this bit, and thought it might be helpful for y'all to see [this nascent plan around dep in CI](https://docs.google.com/document/d/1j_Hka8eFKqWwGJWFSFedtBsNkFaRN3yvL4g8k30PLmg). (comments are very welcome!)

**Comment by cblecker** [comment]
Thanks @sdboyer !
