### PR TITLE
Fix approval case sensitivity

### LINKED ISSUE #2123: Make OWNERS files case-insensitive
Right now the algorithms which checks OWNERS files for approval is matching names taking case into account. It seems to be safe to not care about the case, because GitHub doesn't allow two usernames differ only by case.

### PR DESCRIPTION
**Pull request by apelisse**
Fixes #2123

### CODE REVIEW

File: mungegithub/mungers/approvers/owners.go [hunk 1]
```diff
@@ -188,9 +217,8 @@ type Approvers struct {
 // UnapprovedFiles returns owners files that still need approval
 func (ap Approvers) UnapprovedFiles() sets.String {
 	unapproved := sets.NewString()
-	for fn := range ap.Owners.GetOwnersSet() {
-		approvers := ap.Owners.repo.Approvers(fn)
-		if approvers.Intersection(ap.Approvers).Len() == 0 {
+	for fn, approvers := range ap.Owners.GetApprovalStatus(ap.Approvers) {
+		if len(approvers) == 0 {
```
Comment (grodrigues3) [inline mungegithub/mungers/approvers/owners.go]: we're really overloading the approvers term.  It's a struct, a field within a struct and a commonly used local variable.  Can we use a different var name?

File: mungegithub/mungers/approvers/owners.go [hunk 2]
```diff
@@ -150,6 +151,34 @@ func (o Owners) GetOwnersSet() sets.String {
...
+		if lower.Has(strings.ToLower(item)) {
+			intersection.Insert(item)
+		}
+	}
+	return intersection
+}
+
+// GetApprovalStatus returns a map from files -> list of current approvers.
+func (o Owners) GetApprovalStatus(approvers sets.String) map[string]sets.String {
+	status := map[string]sets.String{}
```
Comment (grodrigues3) [inline mungegithub/mungers/approvers/owners.go]: This kind of contradicts our original design of keeping anything tied to the comments separate from the owners struct (which should only be dependent on the PR).  Can we attach this func to Approvers struct 

`func (a Approvers) GetApprovalStatus`

File: mungegithub/mungers/approvers/owners.go [hunk 3]
```diff
@@ -200,14 +228,13 @@ func (ap Approvers) UnapprovedFiles() sets.String {
 // UnapprovedFiles returns owners files that still need approval
 func (ap Approvers) GetFiles() []File {
 	allOwnersFiles := []File{}
+	status := ap.Owners.GetApprovalStatus(ap.Approvers)
```
Comment (grodrigues3) [inline mungegithub/mungers/approvers/owners.go]: then this becomes

`status := ap.getApprovalStatus()`  

I think it's cleaner

File: mungegithub/mungers/approvers/owners_test.go [hunk 4]
```diff
@@ -669,3 +669,76 @@ func TestRemoveSubdirs(t *testing.T) {
...
+			approvers:      []string{},
+			owners:         map[string]sets.String{},
+			expectedStatus: map[string]sets.String{},
+		},
+		{
+			testName:       "No approvers",
+			filenames:      []string{"a/a", "c"},
+			approvers:      []string{},
+			owners:         map[string]sets.String{"": sets.NewString("RootOwner")},
+			expectedStatus: map[string]sets.String{"": sets.String{}},
```
Comment (grodrigues3) [inline mungegithub/mungers/approvers/owners_test.go]: why isn't there two expected owners files `"a" and "c"`

File: mungegithub/mungers/approvers/owners_test.go [hunk 5]
```diff
@@ -669,3 +669,76 @@ func TestRemoveSubdirs(t *testing.T) {
...
+				"a": sets.NewString("AApprover"),
+				"c": sets.NewString("CApprover"),
+			},
+			expectedStatus: map[string]sets.String{
+				"a": sets.NewString("RootApprover"),
+				"c": sets.NewString("RootApprover", "CApprover"),
+			},
+		},
+		{
+			testName:       "Case-insensitive approvers",
```
Comment (grodrigues3) [inline mungegithub/mungers/approvers/owners_test.go]: which one is supposed to be reflected in the owners files?  Theoretically it should work bidirectionally right?  (Weird caps in owners files or weird capitalization in the comment list).  Can you add a test for the reverse as well? And which should be displayed "RootApprover" or "rOOtaPProver".

File: mungegithub/mungers/approvers/owners.go (hunk 1 above)
Comment (apelisse) [inline mungegithub/mungers/approvers/owners.go]: I agree :-/

File: mungegithub/mungers/approvers/owners.go (hunk 2 above)
Comment (apelisse) [inline mungegithub/mungers/approvers/owners.go]: Yeah, probably. But we are also leaking the repo from Owners inside Approvers which I think is even worse. Let me see if I can find a better way to do that.

Comment (grodrigues3) [inline mungegithub/mungers/approvers/owners.go]: Encapsulation (i.e. write an accessor function to repo)

File: mungegithub/mungers/approvers/owners_test.go (hunk 5 above)
Comment (apelisse) [inline mungegithub/mungers/approvers/owners_test.go]: well, case-insensitive comparison doesn't really have a "direction". So if it matches different case, it's good to go.

I carefully selected that we should use the name/case from the approvers list rather than the name/case from the OWNERS files, but that could be more explicit. The reason is that OWNERS are manually written (hence can contain errors), while the approvers list is generated directly from your exact github handle.

File: mungegithub/mungers/approvers/approvers_test.go [hunk 6]
```diff
@@ -402,3 +403,76 @@ func TestIsApproved(t *testing.T) {
 		}
 	}
 }
+
+func TestGetApprovalStatus(t *testing.T) {
```
Comment (grodrigues3) [inline mungegithub/mungers/approvers/approvers_test.go]: If you change the func name, test name should match

**Comment by MrHohn** [comment]
Thanks for the fix! Is this taking effect now? Just tried it with no luck ([ref](https://github.com/kubernetes/kubernetes/pull/42802#issuecomment-286314322)) :(

**Comment by apelisse** [comment]
Not deployed yet afaik :-(

**Comment by grodrigues3** [comment]
yeah, still being tested on test-infra. @spxtr any rule of thumb before deploying plugins on the main repo

**Comment by pipejakob** [comment]
Hey @grodrigues3, @spxtr is on vacation. You might be able to reach @rmmh, who is the EngProd on-call.

**Comment by apelisse** [comment]
Wait, what? No.

This is in the munger, and it's been deployed a while ago, it should be good now.
