### PR TITLE
mungegithub/approvers fix randomization bug

### LINKED ISSUE #1770: mungebot/Approval: get rid of random seed shuffle; use round robin instead in findApprovers

### PR DESCRIPTION
**Pull request by grodrigues3**
Instead of switching to Round Robin, this should fix the bug.

Our previous implementation was implicitly relying on the order of the keys in a map being fixed, something the go designers explicitly warned against.

fixes #1770

### CODE REVIEW

File: mungegithub/mungers/approval-handler.go [hunk 1]
```diff
@@ -202,13 +202,27 @@ func (h ApprovalHandler) unwrapAliases(ownerSet sets.String) sets.String {
 	return aliases.Expand(ownerSet)
 }
 
+func getRandomizedKeys(approverOwnersfiles map[string]sets.String) []string {
```
Comment (apelisse) [inline mungegithub/mungers/approval-handler.go]: I'd really really like to see a test function before we get this merged.

Also, i see this doesn't depend on a seed, but on the number of files. Does it mean that the same set of files will always lead to the same approver? Is that fair?

File: mungegithub/mungers/approval-handler.go [hunk 2]
```diff
@@ -202,13 +202,27 @@ func (h ApprovalHandler) unwrapAliases(ownerSet sets.String) sets.String {
...
+	sliceOfKeys := make([]string, 0, len(approverOwnersfiles))
+	for approver := range approverOwnersfiles {
+		sliceOfKeys = append(sliceOfKeys, approver)
+	}
+	sort.Strings(sliceOfKeys)
+	order := rand.Perm(len(approverOwnersfiles))
```
Comment (grodrigues3) [inline mungegithub/mungers/approval-handler.go]: this depends on the seed.  so the same set of files will not lead to the same approver

Comment (apelisse) [inline mungegithub/mungers/approval-handler.go]: Wait, the seed is the length of approverOwnersFiles? So if this set of file is the same, it will have the same seed?

Comment (grodrigues3) [inline mungegithub/mungers/approval-handler.go]: No.  That's not the seed.  The seed is set in munge method.

https://golang.org/pkg/math/rand/#Perm

Comment (apelisse) [inline mungegithub/mungers/approval-handler.go]: <- shame shame shame

Comment (apelisse) [inline mungegithub/mungers/approval-handler.go]: I got confused because I would never have expected the seed to be set in another place. Can we make it less confusing  to dumb people like me? :-)

Comment (grodrigues3) [inline mungegithub/mungers/approval-handler.go]: so make the seed a parameter and then pass the prNumber all over the place?  seems gross

Comment (apelisse) [inline mungegithub/mungers/approval-handler.go]: OK Let's keep it like this for now. I agree with you that it's gross :-)

**Comment by apelisse** [comment]
Wait, where is the test?

**Comment by apelisse** [comment]
I think I have somewhat more confidence that this is working :-)
