### PR TITLE
[Approve plugin] Set state fields from PR when handling a review

### LINKED ISSUE #9609: Approve plugin uses incorrect PR state when handling a review event
The `handleReview` method added in #8140 incorrectly uses the review author instead of the PR author in the PR state it sends to `handle`. This causes author self-approval to fail when followed by a review from another user. We can see an example in https://github.com/knative/serving/pull/1882 when @josephburnett adds https://github.com/knative/serving/pull/1882#pullrequestreview-147833118. @mattmoor's author self-approval is cancelled by @josephburnett's subsequent approving review.

This code in `handleReview`:
https://github.com/kubernetes/test-infra/blob/cd3ce57f573af08680ac80e618daa7b79a77f6b9/prow/plugins/approve/approve.go#L247-L248

should actually be the same as its analogue in `handlePullRequest`:
https://github.com/kubernetes/test-infra/blob/cd3ce57f573af08680ac80e618daa7b79a77f6b9/prow/plugins/approve/approve.go#L297-L298

This is not detected by tests added in https://github.com/kubernetes/test-infra/pull/8872 because those tests don't verify the state value passed to `handle`, only that `handle` was called.

I'll submit a PR soon with a verified fix and expanded coverage, just waiting for time to polish up the tests.

/cc @fejta @cjwagner @guineveresaenger

### PR DESCRIPTION
**Pull request by grantr**
Branch, body, and author fields were previously unset or incorrectly sourced from the review instead of the PR. This removed the ability for authors to implicitly self-approve because their authorship was replaced by the author of the currently handled review.

One test for each of `handleGenericComment`, `handleReview`, and `handlePullRequest` now verifies that the state given to `handleFunc` is correct.

Fixes #9609.

/cc @fejta @cjwagner @guineveresaenger @stevekuznetsov

### CODE REVIEW

File: prow/plugins/approve/approve.go [hunk 1]
```diff
@@ -243,9 +243,10 @@ func handleReview(log *logrus.Entry, ghc githubClient, oc ownersClient, config *
 		&state{
 			org:       re.Repo.Owner.Login,
 			repo:      re.Repo.Name,
+			branch:    pr.Base.Ref,
 			number:    re.PullRequest.Number,
-			body:      re.Review.Body,
-			author:    re.Review.User.Login,
+			body:      re.PullRequest.Body,
```
Comment (cjwagner) [inline prow/plugins/approve/approve.go]: This just made me realize that we shouldn't be calling `GetPullRequest` above! We can just use `re.PullRequest` where ever `pr` is used in this function and avoid spending an API token.

Comment (grantr) [reply prow/plugins/approve/approve.go]: Thanks for noticing that! I noticed it myself but decided to leave it to keep the diff small :)
