### PR TITLE
Do not add do not merge label when PR is merged

### LINKED ISSUE #23205: release-note check the merged PR and label 'do-not-merge'
**What happened**:

When the body of an already merged PR is modified, release-note checks that pr does not contain release-note block, and then adds a `do-not-merge/release-note-label-needed`, which looks a little strangeness.

**What you expected to happen**:

Can we ignore the check on the PR that has been merged?

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

Related PR: https://github.com/pingcap/tidb/pull/23982#issuecomment-896748369

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by jmguzik**
This commit fixes the issue described in #23205. Release note plugin
should not label the PR when it is already merged.

/fixes #23205

Signed-off-by: Jakub Guzik <jguzik@redhat.com>

### CODE REVIEW

File: prow/plugins/releasenote/releasenote.go [hunk 1]
```diff
@@ -275,7 +275,7 @@ func handlePR(gc githubClient, log *logrus.Entry, pr *github.PullRequestEvent) e
 			}
 			if containsNoneCommand(comments) {
 				labelToAdd = labels.ReleaseNoteNone
-			} else if !prLabels.Has(labels.ReleaseNoteLabelNeeded) {
+			} else if !prLabels.Has(labels.ReleaseNoteLabelNeeded) && !pr.PullRequest.Merged {
```
Comment (petr-muller) [inline prow/plugins/releasenote/releasenote.go:278]: So this prevents adding a comment but not the label (which the issue is about). Maybe we should discard events on merged PRs sooner? Is there even any valid action when then the PR is merged?

**Review by petr-muller — COMMENTED** [review]
/ok-to-test

File: prow/plugins/releasenote/releasenote.go (hunk 1 above)
Comment (jmguzik) [reply prow/plugins/releasenote/releasenote.go:278]: About the first one, I noticed it and was about to modify the change.
Regarding the actions, I will look into it. Not sure if possible.

Comment (jmguzik) [reply prow/plugins/releasenote/releasenote.go]: Ok, hopefully, moved this condition to a better place.

File: prow/plugins/releasenote/releasenote.go [hunk 2]
```diff
@@ -226,10 +226,10 @@ func shouldHandlePR(pr *github.PullRequestEvent) bool {
 		return false
 	}
 
-	// Ignoring unrelated PR labels prevents duplicate release note messages
+	// Ignoring unrelated PR labels prevents duplicate release note messages, merged PRs also ignored
 	if pr.Action == github.PullRequestActionLabeled {
 		for _, rnLabel := range allRNLabels {
-			if pr.Label.Name == rnLabel {
+			if pr.Label.Name == rnLabel && !pr.PullRequest.Merged {
```
Comment (petr-muller) [inline prow/plugins/releasenote/releasenote.go:232]: So we still fire on `Edited` though? And if *that* is desired, why bother with iterating?

Not sure about the actual logic TBH. I think it is just never right to add the actual `do-not-merge/...` label (and probably an associated comment) on a merged PR, but that's it. So personally, I'd focus on specifically not adding  that label when the PR is merged.

I don't know the expectations for the other labels, so I'd keep their behavior as it is.

File: prow/plugins/releasenote/releasenote.go [hunk 3]
```diff
@@ -219,6 +219,11 @@ func handlePullRequest(pc plugins.Agent, pr github.PullRequestEvent) error {
 }
 
 func shouldHandlePR(pr *github.PullRequestEvent) bool {
+	//Do not handle the PR when it's merged
```
Comment (jmguzik) [inline prow/plugins/releasenote/releasenote.go:222]: Actually, I was certain this is the case, but after a second look round, not so sure. Let me think about this before further discussion

File: prow/plugins/releasenote/releasenote.go (hunk 2 above)
Comment (jmguzik) [reply prow/plugins/releasenote/releasenote.go]: I misunderstood initially your comment but I think, probably the condition should be like:

` if pr.Action == github.PullRequestActionLabeled && !pr.PullRequest.Merged `

We still fire on edited in my opinion.

Comment (jmguzik) [reply prow/plugins/releasenote/releasenote.go]: implemented

File: prow/plugins/releasenote/releasenote.go [hunk 4]
```diff
@@ -219,6 +219,11 @@ func handlePullRequest(pc plugins.Agent, pr github.PullRequestEvent) error {
...
+	if pr.PullRequest.Merged {
```
Comment (jmguzik) [inline prow/plugins/releasenote/releasenote.go:223]: I think it's safe to say do not handle the PR since it's merged.  HandlePR function is all about adding and removing labels (also posting comments related to labels), so it's not needed for a merged PR.

File: prow/plugins/releasenote/releasenote.go [hunk 5]
```diff
@@ -255,6 +255,11 @@ func handlePR(gc githubClient, log *logrus.Entry, pr *github.PullRequestEvent) e
 	var comments []github.IssueComment
 	labelToAdd := determineReleaseNoteLabel(pr.PullRequest.Body, prLabels)
 
+	//Do not handle ReleaseNoteLabelNeeded do not merge label when the PR is merged
+	if labelToAdd == labels.ReleaseNoteLabelNeeded && pr.PullRequest.Merged {
```
Comment (jmguzik) [inline prow/plugins/releasenote/releasenote.go:259]: I think now it should be ok. Analyzed all do-not-merge flags in this relm and it seems so this one is the only that could occur inside the function. So, if flag and merged we should stop.

Comment (petr-muller) [reply prow/plugins/releasenote/releasenote.go:259]: nit: the `labelToAdd == labels.ReleaseNoteLabelNeeded` part is the same like in the `if` below so maybe it would be simpler to add a 
```
if pr.PullRequest.Merged {
  return nil
}
``` 

there but /shrug

**Review by petr-muller — APPROVED** [review]

File: prow/plugins/releasenote/releasenote.go (hunk 5 above)
Comment (jmguzik) [reply prow/plugins/releasenote/releasenote.go]: @petr-muller you are right. I am an if-else master. Corrected now.

**Review by petr-muller — APPROVED** [review]

**Review by fejta — APPROVED** [review]
