### PR TITLE
Make it possible to manually trigger RunIfChanged jobs that do not need to run.

### LINKED ISSUE #5069: "skipped" status is acting up
I've observed today:

- PRs that should have `pull-kubernetes-cross` labeled as skipped (anything that doesn't touch build / the run_if_changed specifier) are sometimes showing "waiting on status"
- In https://github.com/kubernetes/kubernetes/pull/54051 I observed that upon `/test pull-kubernetes-bazel-test`, `pull-kubernetes-bazel-test` jumped down to green with "skipped" for ~30s (ish?) before it went to "job triggered"

### LINKED ISSUE #5833: run_if_changed jobs cannot be manually triggered on PRs that do not match
https://github.com/kubernetes/kubernetes/pull/56554

It seems tentatively that `/test pull-kubernetes-cross` doesn't work since this job doesn't change any files matching the regex. I think we had a discussion about this previously in the comments on another PR but I don't have it handy. This is a regression we should probably sort out AFAIK.

/area prow
/cc @cjwagner @kargakis

### PR DESCRIPTION
**Pull request by cjwagner**
fixes #5833
discussion ref #5655 
/cc @BenTheElder @stevekuznetsov 

Also fixes #5069 
The first bullet in that issue should already be fixed by previous PRs. The second bullet should be fixed by this PR:
> In kubernetes/kubernetes#54051 I observed that upon /test pull-kubernetes-bazel-test, pull-kubernetes-bazel-test jumped down to green with "skipped" for ~30s (ish?) before it went to "job triggered"

It looks like the problem was probably branch-sharded jobs. Versions of the job that don't apply to the branch would mark the context as "Skipped" before `plank` could create/report the prowjob for the version that is actually supposed to run.

### CODE REVIEW

File: prow/plugins/trigger/ic.go [hunk 1]
```diff
@@ -155,22 +155,18 @@ func handleIC(c client, trustedOrg string, ic github.IssueCommentEvent) error {
...
-			if err != nil {
-				return err
-			}
-			if !job.RunsAgainstChanges(changes) {
-				build = false
-			}
-		}
-		if !build {
-			if !job.SkipReport {
+			if !job.SkipReport && !anyShardRunsAgainstBranch[job.Context] {
```
Comment (kargakis) [inline prow/plugins/trigger/ic.go]: Isn't `!anyShardRunsAgainstBranch[job.Context]` always going to be `true` at this point?

Comment (cjwagner) [reply prow/plugins/trigger/ic.go]: Not necessarily, we don't check that the jobs run against the current branch before adding them to the `requestedJobs` list because we may still need to mark them as 'Skipped'. So it is possible that no requested versions of a given job run on the branch.

Comment (BenTheElder) [reply prow/plugins/trigger/ic.go]: Adding to what @cjwagner said: we definitely have jobs that need a skipped status marked that are also sharded, the gpu job only runs against 1.7+ and has different 1.7,1.8, 1.9/master versions last I checked.

**Comment by BenTheElder** [comment]
If there are no further concerns can we merge & deploy this?
I'd also like to get pull-kubernetes-cross back on the required list soon.. :smile:

**Comment by cjwagner** [comment]
I'll add a hook bump and roll it out.
