### PR TITLE
Make Tide specify offending values when complaining about duplicates in config.

### LINKED ISSUE #9764: prow: tide: config validation error messages not useful
I don't have enough information from this error to do anything with it

```
{"component":"branchprotector","error":"tide query (index 0) is invalid: 'repos' contains 1 duplicate entries","level":"fatal","msg":"Failed to load --config-path=/home/skuznets/releasego/src/github.com/openshift/release/cluster/ci/config/prow/config.yaml","time":"2018-10-11T09:19:19+02:00"}
```

/kind bug
/area prow/tide
/assign @cjwagner

### PR DESCRIPTION
**Pull request by cjwagner**
fixes #9764 
/assign @stevekuznetsov 

Example of the new error output:
```
Could not load config: tide query (index 2) is invalid: 'repos' contains 1 duplicate entries: [kubernetes/komposer]
```

I also expanded the validation to check for duplicates in the label and branch fields.

### CODE REVIEW

File: prow/config/tide.go [hunk 1]
```diff
@@ -292,7 +292,25 @@ func (qm *QueryMap) ForRepo(org, repo string) TideQueries {
...
+				dupCount++
+				dups.Insert(elem)
+			} else {
+				seen.Insert(elem)
+			}
+		}
+		if dupCount == 0 {
+			return nil
+		}
+		return fmt.Errorf("'%s' contains %d duplicate entries: %s", field, dupCount, dups.List())
```
Comment (fejta) [inline prow/config/tide.go]: %q to quote?
strings.Join() for the List()?

File: prow/config/tide.go [hunk 2]
```diff
@@ -292,7 +292,25 @@ func (qm *QueryMap) ForRepo(org, repo string) TideQueries {
...
+		seen := sets.NewString()
+		for _, elem := range list {
+			if seen.Has(elem) {
+				dupCount++
+				dups.Insert(elem)
+			} else {
+				seen.Insert(elem)
+			}
+		}
+		if dupCount == 0 {
```
Comment (stevekuznetsov) [inline prow/config/tide.go]: Technically you could just use `len(list) - len(seen.UnorderedList())` instead of tracking the number of dupes

File: prow/config/tide.go (hunk 1 above)
Comment (cjwagner) [reply prow/config/tide.go]: I was trying to avoid all the quote escaping in the logs, but I guess that doesn't really matter. Fixed.

File: prow/config/tide.go (hunk 2 above)
Comment (cjwagner) [reply prow/config/tide.go]: :man_facepalming: Fixed.
