### PR TITLE
Make Tide omit PRs failing GitHub contexts from the pool.

### LINKED ISSUE #7279: Change how Tide handles jobs with failing tests.
Tide doesn't really handle PRs with failing tests very well:
- PRs can appear in Tide's "Passing" column if they have failing status contexts that are not controlled by Tide (e.g. code coverage statuses or reviewable statuses).
- PRs that meet all label requirements, but have failing tests are considered to be in the tide pool, but won't become mergeable because Tide won't automatically retest PRs with failing tests. This is confusing. It would be better if the PR's 'tide' context indicated that it was unmergeable due to a test failure and it should not appear on the Tide dashboard.

We can't just limit the tide query to PRs that have all statuses passing, because that would exclude PRs where all contexts are passing except the Tide context. However, we can filter out PRs with failing status contexts locally and ignore the 'tide' context (and any other contexts we want to ignore).

If we filter out failing PRs from the pool before syncing and setting statuses, the Tide dashboard won't show failing PRs and the 'tide' status context will show that failing PRs are not mergeable. We can also improve the status description to mention which contexts are failing if that is actually useful.

Please let me know if this seems reasonable.
/area prow
/kind bug
/assign
/cc @spxtr @kargakis @stevekuznetsov @BenTheElder

### PR DESCRIPTION
**Pull request by cjwagner**
Previously PRs that were failing, but otherwise mergeable were included
in the pool. Now they are filtered out of the pool before subpools are
synced and before the pool is given to the status controller.
Importantly, we allow PRs with unsuccessful statuses to remain in the
pool so long as all unsuccessful statuses are pending contexts
associated with ProwJobs that are required for merge.

This should fix the problem that TIde encountered on openshift/origin where PRs that were missing contexts from a new job were considered to be in the pool, but weren't considered to be passing status contexts and were thus untestable. After these changes, those PRs would be marked as not in the pool and the status context will point to the missing job.

This also fixes some other minor bugs. I have a bunch of other cleanup and bug fixes that I will complete in follow up PRs.

fixes #7279 
/area prow
/kind bug
/cc @stevekuznetsov @kargakis @sebastienvas

### CODE REVIEW

File: prow/tide/tide.go [hunk 1]
```diff
@@ -275,6 +282,74 @@ func (c *Controller) ServeHTTP(w http.ResponseWriter, r *http.Request) {
...
+		}
+
+		if spFiltered := filterSubpool(c.ghc, sp); spFiltered != nil {
+			filtered[key] = spFiltered
+		}
+	}
+	return filtered
+}
+
+func filterSubpool(ghc githubClient, sp *subpool) *subpool {
```
Comment (kargakis) [inline prow/tide/tide.go]: godoc what the filter does

Comment (cjwagner) [reply prow/tide/tide.go]: Done. Any other comments?

**Comment by kargakis** [comment]
I am wondering how much more token usage will the usage of `headContexts` add here and whether this is an issue that goes away with the github cache.

**Comment by rmmh** [comment]
headContexts only costs quota in the rare case that commits aren't chronologically ordered, so GitHub returns the "wrong" last commit-- otherwise they're included in the GraphQL query.

**Comment by cjwagner** [comment]
+1 To what Ryan said. There is an additional change I am making now so that we only ever have to make an extra API call if the commits aren't chronologically ordered **and** the base ref has been deleted (the intersection of these two events should be very rare).

> whether this is an issue that goes away with the github cache

The github cache does make this mostly a non-issue for our use cases, but we shouldn't rely on it. I hope that we can keep it an optional component.

**Comment by kargakis** [comment]
> The github cache does make this mostly a non-issue for our use cases, but we shouldn't rely on it. I hope that we can keep it an optional component.

+1

**Comment by cjwagner** [comment]
Here is the PR to improve token usage related to fetching head commit status contexts: https://github.com/kubernetes/test-infra/pull/8550

Any more reviews for this PR? Please stamp if not.

**Comment by cjwagner** [comment]
I made a small change to reuse the `presubmit` map and `cc` context checker instead of recreating them.

File: prow/tide/tide.go [hunk 2]
```diff
@@ -275,6 +282,83 @@ func (c *Controller) ServeHTTP(w http.ResponseWriter, r *http.Request) {
...
+	}
+	return filtered
+}
+
+// filterSubpool filters PRs from an initially identified subpool. If the subpool
+// becomes empty 'nil' is returned.
+// Specifically we filter out PRs that:
+// - Have known merge conflicts.
+// - Have failing or missing status contexts.
+// - Have pending status contexts that are not associated with a required ProwJob.
```
Comment (kargakis) [inline prow/tide/tide.go]: Will this break merging PRs that don't use prow for testing?

File: prow/tide/tide.go [hunk 3]
```diff
@@ -275,6 +282,83 @@ func (c *Controller) ServeHTTP(w http.ResponseWriter, r *http.Request) {
...
+func filterSubpool(ghc githubClient, sp *subpool) *subpool {
+	var toKeep []PullRequest
+PRLOOP:
```
Comment (stevekuznetsov) [inline prow/tide/tide.go]: If you make a `func prShouldBeFiltered(githubClient, pr) (bool, err)` and call it in the outer loop you won't need this label

File: prow/tide/tide.go (hunk 2 above)
Comment (stevekuznetsov) [reply prow/tide/tide.go]: Won't it just wait until the non-Prow controlled status is resolved to something other than `pending`?

**Comment by stevekuznetsov** [comment]
@cjwagner ping -- this has bitten us a couple times now

File: prow/tide/tide.go (hunk 2 above)
Comment (cjwagner) [reply prow/tide/tide.go]: Exactly what Steve said. I figured we shouldn't consider those PRs part of the pool until the statuses that are out of our control (but are required) are all green since Tide won't be able to merge until they are green and Tide can't retrigger those tests itself.

File: prow/tide/tide.go (hunk 3 above)
Comment (cjwagner) [reply prow/tide/tide.go]: Fixed.

**Comment by cjwagner** [comment]
Comments addressed, PTAL.
