### PR TITLE
Make Tide batches fail fast

### LINKED ISSUE #9724: fast-fail batches in tide
currently the batch results look like:
image
yet the tide dashboard is:
image

why are we not merging 69386 now that the batch has failed a required test? are we waiting for all of the jobs in the batch to complete ...?

/kind question
/area tide
probably:
/kind bug

/assign @cjwagner

### PR DESCRIPTION
**Pull request by cjwagner**
fixes #9724 

Previously we reported a pending batch as soon as we found a pending batch job, even if other jobs in the batch had failed. Now we determine the overall state for each batch before reporting a batch as pending. We also return both the pending batch and the successful batch if both are present.

/assign @BenTheElder @stevekuznetsov 
/kind bug

### CODE REVIEW

**Comment by BenTheElder** [comment]
Thanks for the quick fix! I will come back to this soon 👍

File: prow/tide/tide.go [hunk 1]
```diff
@@ -600,20 +595,27 @@ func accumulateBatch(presubmits map[int]sets.String, prs []PullRequest, pjs []ku
 		for _, pr := range state.prs {
 			requiredPresubmits = requiredPresubmits.Union(presubmits[int(pr.Number)])
 		}
-		passesAll := true
+		overallState := successState
 		for _, p := range requiredPresubmits.List() {
-			if s, ok := state.jobStates[p]; !ok || s != successState {
-				passesAll = false
-				log.WithField("batch", ref).Debugf("batch invalid, required presubmit %s not passing", p)
+			s, ok := state.jobStates[p]
```
Comment (stevekuznetsov) [inline prow/tide/tide.go]: Nit: This could remain inline with the `if`

File: prow/tide/tide_test.go [hunk 2]
```diff
@@ -80,22 +80,31 @@ func TestAccumulateBatch(t *testing.T) {
...
 			pending:    true,
 		},
+		{
+			name:       "pending batch missing presubmits is ignored",
+			presubmits: map[int]sets.String{1: jobSet},
+			pulls:      []pull{{1, "a"}, {2, "b"}},
+			prowJobs:   []prowjob{{job: "foo", state: kube.PendingState, prs: []pull{{1, "a"}}}},
+		},
 		{
 			name:       "batch pending, successful previous run",
```
Comment (stevekuznetsov) [inline prow/tide/tide_test.go]: I think I'm misunderstanding this test - if PR 2 succeeded but we have a pending batch, shouldn't we still wait, not merge 2?

Comment (cjwagner) [reply prow/tide/tide_test.go]: What is the benefit of waiting for a pending batch to complete if we already have a successful batch that we can merge? Once we add support for triggering multiple batches of different sizes we'll want to update this to consider the size of the batches, but for now it seems appropriate to just merge the successful batch. Note that we are not triggering multiple batches currently so this case shouldn't really occur anyways.

File: prow/tide/tide.go (hunk 1 above)
Comment (cjwagner) [reply prow/tide/tide.go]: Fixed.

File: prow/tide/tide_test.go (hunk 2 above)
Comment (stevekuznetsov) [reply prow/tide/tide_test.go]: Oh, as there was only one PR, I thought there was one batch and one singleton test. As they're both batches, that makes sense

**Comment by stevekuznetsov** [comment]
/lgtm
/hold
@bentheelder did you want a look?
