### PR TITLE
Cancel pipeline when triggering a new test run

### LINKED ISSUE #28720: Cancelling prowjob should cancel the tekton pipelineRun as well
**What happened**:
We added the tekton pipelines support for `v1beta1` recently and its working great.
The only piece missing right now is cleanup. 
Whenever a new prowjob is created for the same PR, the previous prowjob is cancelled, which is the expected behavior.
However for prowjobs using the `tekton-pipeline` agent, only the prowjob cancels while the pipelineRun continues running.

**What you expected to happen**:
Whenever a new prowjob is created for the same PR, the previous prowjob is cancelled along with its pipelineRun and its pods.

**How to reproduce it (as minimally and precisely as possible)**:
Create a prowjob that uses a tekton-pipeline. Create a PR and the job runs as expected. Push a new commit or rerun the same job with `/test jobname` which should start a new job, leaving the previous pipeline running

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by jmguzik**
/fixes #28720

### CODE REVIEW

**Comment by jmguzik** [comment]
@cjwagner @droslean maybe you could find time to review this one (yeah I know it's a niche topic).
/cc @droslean

File: prow/cmd/pipeline/controller.go [hunk 1]
```diff
@@ -36,11 +37,13 @@ import (
 	"k8s.io/test-infra/prow/pod-utils/downwardapi"
 
 	"github.com/sirupsen/logrus"
+	"github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1"
```
Comment (petr-muller) [inline prow/cmd/pipeline/controller.go:40]: We already import this on the line below

File: prow/cmd/pipeline/controller.go [hunk 2]
```diff
@@ -300,6 +305,15 @@ func (c *controller) patchProwJob(pj *prowjobv1.ProwJob, newpj *prowjobv1.ProwJo
 	return pjutil.PatchProwjob(context.TODO(), c.pjc.ProwV1().ProwJobs(c.pjNamespace()), logrus.NewEntry(logrus.StandardLogger()), *pj, *newpj)
 }
 
+func (c *controller) listProwJobs(namespace string) ([]*prowjobv1.ProwJob, error) {
+	pjnl := c.pjLister.ProwJobs(namespace)
+	pjs, err := pjnl.List(labels.NewSelector())
+	if err != nil {
+		return nil, err
+	}
+	return pjs, nil
```
Comment (petr-muller) [inline prow/cmd/pipeline/controller.go:314]: I'd say you could simply `return pjnl.List(labels.NewSelector())` here, the caller is still supposed to test `err` and avoid using the returned value /shrug

File: prow/cmd/pipeline/controller.go [hunk 3]
```diff
@@ -317,6 +331,18 @@ func (c *controller) deletePipelineRun(pContext, namespace, name string) error {
 	return p.client.TektonV1beta1().PipelineRuns(namespace).Delete(context.TODO(), name, metav1.DeleteOptions{})
 }
 
+func (c *controller) cancelPipelineRun(pContext string, pr *pipelinev1beta1.PipelineRun) (*pipelinev1beta1.PipelineRun, error) {
```
Comment (petr-muller) [inline prow/cmd/pipeline/controller.go:334]: I read `pr` and think Pull Request, can we use a different abbreviation? :P

File: prow/cmd/pipeline/controller.go [hunk 4]
```diff
@@ -317,6 +331,18 @@ func (c *controller) deletePipelineRun(pContext, namespace, name string) error {
...
+	p, err := c.getPipelineConfig(pContext)
+	if err != nil {
+		return nil, err
+	}
+	if pr.Spec.Status == pipelinev1beta1.PipelineRunSpecStatusCancelled {
+		return pr, nil
+	}
+	pr.Spec.Status = pipelinev1beta1.PipelineRunSpecStatusCancelled
+	return p.client.TektonV1beta1().PipelineRuns(pr.Namespace).Update(context.TODO(), pr, metav1.UpdateOptions{})
```
Comment (petr-muller) [inline prow/cmd/pipeline/controller.go:343]: I'd say that this should actually use a passed-in context instead of `context.TODO()`, otherwise how would we cancel?

Comment (petr-muller) [reply prow/cmd/pipeline/controller.go:343]: Oh, I see, the existing code already does not care... :unamused: I'd still like new code to do better, wdyt?

File: prow/cmd/pipeline/controller.go [hunk 5]
```diff
@@ -352,6 +378,61 @@ func (c *controller) pipelineID(pj prowjobv1.ProwJob) (string, string, error) {
...
+	var additionalIdentifier string
+	if pj.Spec.Refs != nil {
+		var pulls []int
+		for _, pull := range pj.Spec.Refs.Pulls {
+			pulls = append(pulls, pull.Number)
+		}
+		sort.Ints(pulls)
+		additionalIdentifier = fmt.Sprintf("%s/%s@%s %v", pj.Spec.Refs.Org, pj.Spec.Refs.Repo, pj.Spec.Refs.BaseRef, pulls)
+	}
+	return fmt.Sprintf("%s %s", pj.Spec.Job, additionalIdentifier)
```
Comment (petr-muller) [inline prow/cmd/pipeline/controller.go:391]: nit: this identifier is only used internally, right? never serialized and never shown to a user. I'm thinking it could be at least loggable: with no pulls or without refs the identifier will have a dangling space...

File: prow/cmd/pipeline/controller.go [hunk 6]
```diff
@@ -352,6 +378,61 @@ func (c *controller) pipelineID(pj prowjobv1.ProwJob) (string, string, error) {
...
+		}
+	}
+	sort.Slice(pjs, func(i, j int) bool {
+		return pjs[i].Status.StartTime.Before(&pjs[j].Status.StartTime)
+	})
+	return pjs
+}
+
+func abortDuplicatedProwJobs(c reconciler, pj *prowjobv1.ProwJob) (*prowjobv1.ProwJob, error) {
+	if !runningState(pj.Status.State) || pj.Spec.Agent != prowjobv1.TektonAgent {
```
Comment (petr-muller) [inline prow/cmd/pipeline/controller.go:408]: what if we are still pending or something? we should still abort IMO.

File: prow/cmd/pipeline/controller.go [hunk 7]
```diff
@@ -416,9 +502,16 @@ func reconcile(c reconciler, key string) error {
 	case finalState(pj.Status.State):
 		logrus.Infof("Observed finished: %s", key)
 		return nil
+	case cancelledState(pj.Status.State):
+		if p != nil && p.Spec.Status != v1beta1.PipelineRunSpecStatusCancelled {
```
Comment (petr-muller) [inline prow/cmd/pipeline/controller.go:506]: `p.Spec.Status` looks weird to me but I guess it's some domain api quirk :)

File: prow/cmd/pipeline/controller.go [hunk 8]
```diff
@@ -416,9 +502,16 @@ func reconcile(c reconciler, key string) error {
...
+			if _, err = c.cancelPipelineRun(ctx, p); err != nil {
```
Comment (petr-muller) [inline prow/cmd/pipeline/controller.go:507]: So why does `cancel` return an instance when the only caller discards it?

File: prow/cmd/pipeline/controller.go [hunk 9]
```diff
@@ -477,10 +570,24 @@ func updateProwJobState(c reconciler, key string, newPipelineRun bool, pj *prowj
...
-	case "", prowjobv1.PendingState, prowjobv1.TriggeredState:
-		return false
+	case prowjobv1.SuccessState, prowjobv1.FailureState, prowjobv1.ErrorState:
+		return true
 	}
-	return true
+	return false
+}
+
+// runningState returns true if the prowjob has already finished
```
Comment (petr-muller) [inline prow/cmd/pipeline/controller.go:579]: This does not seem to be correct godoc

File: prow/cmd/pipeline/controller.go (hunk 2 above)
Comment (jmguzik) [reply prow/cmd/pipeline/controller.go:314]: good catch!

File: prow/cmd/pipeline/controller.go (hunk 3 above)
Comment (jmguzik) [reply prow/cmd/pipeline/controller.go:334]: I used the existing abbreviation but I can change it as well, no problem.

File: prow/cmd/pipeline/controller.go (hunk 4 above)
Comment (jmguzik) [reply prow/cmd/pipeline/controller.go:343]: This is on my list of fixes for the following PRs (with introducing a better interface for prowjob client, replacing the interface used here) so I would vote to leave it as it is and address it in the followup in the future.

File: prow/cmd/pipeline/controller.go (hunk 5 above)
Comment (jmguzik) [reply prow/cmd/pipeline/controller.go:391]: yeah, it is used internally only, but the concept is kind of borrowed from the reconciler from the plank. I think I can remove the space, it was mindless process - the creation of this identifier :)

File: prow/cmd/pipeline/controller.go [hunk 10]
```diff
@@ -352,6 +378,61 @@ func (c *controller) pipelineID(pj prowjobv1.ProwJob) (string, string, error) {
...
+		sort.Ints(pulls)
+		additionalIdentifier = fmt.Sprintf("%s/%s@%s %v", pj.Spec.Refs.Org, pj.Spec.Refs.Repo, pj.Spec.Refs.BaseRef, pulls)
+	}
+	return fmt.Sprintf("%s %s", pj.Spec.Job, additionalIdentifier)
+}
+
+func getFilteredProwJobs(id string, pjsToFilter []*prowjobv1.ProwJob) []*prowjobv1.ProwJob {
+	pjs := []*prowjobv1.ProwJob{}
+	for _, p := range pjsToFilter {
+		if runningState(p.Status.State) && id == createProwJobIdentifier(p) {
```
[the remark this answers is not in the document]
Comment (jmguzik) [reply prow/cmd/pipeline/controller.go:397]: `runningState` function means `pending` and triggered `states`

File: prow/cmd/pipeline/controller.go [hunk 11]
```diff
@@ -352,6 +378,61 @@ func (c *controller) pipelineID(pj prowjobv1.ProwJob) (string, string, error) {
...
+			pjs = append(pjs, p)
+		}
+	}
+	sort.Slice(pjs, func(i, j int) bool {
+		return pjs[i].Status.StartTime.Before(&pjs[j].Status.StartTime)
+	})
+	return pjs
+}
+
+func abortDuplicatedProwJobs(c reconciler, pj *prowjobv1.ProwJob) (*prowjobv1.ProwJob, error) {
```
[the remark this answers is not in the document]
Comment (jmguzik) [reply prow/cmd/pipeline/controller.go:407]: well, I could maybe could think it better but with the prowjob interface I have in this tool, I really could not, at least at that time. It's because it marks every older job, including the one that is currently invoking the function (if it's older than any job in the future) as aborted. So it can technically modify a job that was just acquired from get if a new job appears.

File: prow/cmd/pipeline/controller.go (hunk 6 above)
Comment (jmguzik) [reply prow/cmd/pipeline/controller.go:408]: this function means any running so pending and triggered are counted as well

File: prow/cmd/pipeline/controller.go [hunk 12]
```diff
@@ -352,6 +378,61 @@ func (c *controller) pipelineID(pj prowjobv1.ProwJob) (string, string, error) {
...
+	if !runningState(pj.Status.State) || pj.Spec.Agent != prowjobv1.TektonAgent {
+		return pj, nil
+	}
+	id := createProwJobIdentifier(pj)
```
[the remark this answers is not in the document]
Comment (jmguzik) [reply prow/cmd/pipeline/controller.go:411]: I would analyze and see how much of a change that is. I also do not have a strong opinion. This idea was borrowed from plank reconciler I think.

File: prow/cmd/pipeline/controller.go [hunk 13]
```diff
@@ -352,6 +378,61 @@ func (c *controller) pipelineID(pj prowjobv1.ProwJob) (string, string, error) {
...
+		newpj.Status.Description = descAborted
+		newpj.Status.CompletionTime = &now
+		newpj, err = c.patchProwJob(pjs[i], newpj)
+		if err != nil {
+			logrus.WithError(err).Error("failed abort prowJob")
+			continue
+		}
+		if id == createProwJobIdentifier(pjs[i]) && pj.Status.StartTime == pjs[i].Status.StartTime {
+			pj = newpj.DeepCopy()
+		}
```
[the remark this answers is not in the document]
Comment (jmguzik) [reply prow/cmd/pipeline/controller.go:431]: This is a special rare case. If the prowjob that is currently passed to the function is on the list of prowjobs to be changed and was updated... it means we have an older definition and we need to update it as later we will interact with tekton upon the actual and up-to-date information from that pj (there is a big switch-case later on that utilizes up to date info). So if pj passed to a function is aborted we need to upgrade it definition.

File: prow/cmd/pipeline/controller.go (hunk 8 above)
Comment (jmguzik) [reply prow/cmd/pipeline/controller.go:507]: The function underneath (patch tekton something...) returns it, but it could be removed as well. What do you prefer?

File: prow/cmd/pipeline/controller.go (hunk 9 above)
Comment (jmguzik) [reply prow/cmd/pipeline/controller.go:579]: haha yes, thanks!

File: prow/cmd/pipeline/controller.go (hunk 11 above)
[the remark this answers is not in the document]
Comment (jmguzik) [reply prow/cmd/pipeline/controller.go:407]: Just came to my mind that all patch operations return something and it's just another form of patch, with abort status.

File: prow/cmd/pipeline/controller.go (hunk 4 above)
Comment (petr-muller) [reply prow/cmd/pipeline/controller.go:343]: Yeah, that sounds good to me

File: prow/cmd/pipeline/controller.go (hunk 5 above)
Comment (petr-muller) [reply prow/cmd/pipeline/controller.go:391]: no worries - if this concept is used elsewhere then I'm fine with it

File: prow/cmd/pipeline/controller.go (hunk 10 above)
[the remark this answers is not in the document]
Comment (petr-muller) [reply prow/cmd/pipeline/controller.go:397]: it's a little confusing to read at the callsite. I would not expect "running" to include "pending" but whatever, I don't immediately see a better name so /shrug

File: prow/cmd/pipeline/controller.go (hunk 12 above)
[the remark this answers is not in the document]
Comment (petr-muller) [reply prow/cmd/pipeline/controller.go:411]: I think the identifier approach is a little clunky and could be improved to read better but I do not worry too much about it. Especially if the same approach is used elsewhere (I did not know that).

File: prow/cmd/pipeline/controller.go (hunk 11 above)
[the remark this answers is not in the document]
Comment (petr-muller) [reply prow/cmd/pipeline/controller.go:407]: I am not entirely convinced I like it but if you can add a line of godoc about expected return value then I'm good with it

File: prow/cmd/pipeline/controller.go (hunk 8 above)
Comment (petr-muller) [reply prow/cmd/pipeline/controller.go:507]: I'd prefer to remove it if it isn't used

File: prow/cmd/pipeline/controller.go (hunk 13 above)
[the remark this answers is not in the document]
Comment (petr-muller) [reply prow/cmd/pipeline/controller.go:431]: Hm... ok. That explains 2) -  I think it would be useful to add a comment here about it (basically what you wrote). 

Still, 1) applies, right? And I wonder whether we could match on something more explicit than `StartTime`, why don't we match on `pj.ObjectMeta.Name` or `pj.ObjectMeta.UID`?

[the remark this answers is not in the document]
Comment (jmguzik) [reply prow/cmd/pipeline/controller.go:431]: good question, I think names should be the same so I can change it to name. I do not have an explanation for why I thought id and start time are better ¯\_(ツ)_/¯

File: prow/cmd/pipeline/controller.go (hunk 11 above)
[the remark this answers is not in the document]
Comment (jmguzik) [reply prow/cmd/pipeline/controller.go:407]: I added godoc

File: prow/cmd/pipeline/controller.go (hunk 13 above)
[the remark this answers is not in the document]
Comment (jmguzik) [reply prow/cmd/pipeline/controller.go]: changed to Name

File: prow/cmd/pipeline/controller.go (hunk 12 above)
[the remark this answers is not in the document]
Comment (jmguzik) [reply prow/cmd/pipeline/controller.go:411]: I left the identifier at the end.

**Comment by jmguzik** [comment]
@petr-muller I think I applied almost all of your comments. PTAL in your free time.

**Review by qaifshaikh — APPROVED** [review]

**Review by petr-muller — APPROVED** [review]

**Comment by emirot** [comment]
@jmguzik that's a great feature, thank you.
I have some questions:
- if I understand correctly, it will cancel previous tekton pipelinerun if a previous one is running and let the newer one running?
- In which version this been added ?
- What if we want to keep previous ones for some specific use case in a repo is that possible?
