### PR TITLE
Fix multi command comment

### LINKED ISSUE #1672: Mungebot: Only one command is parsed from comment
As people may want to approve and lgtm at the same time, it would be easier for them to do so if they can type multiple commands in the same comment. They currently can't do that.

### PR DESCRIPTION
**Pull request by apelisse**
Fixes #1672 and #1673 and some unreported bugs

### CODE REVIEW

File: mungegithub/mungers/matchers/comment/command.go [hunk 1]
```diff
@@ -34,25 +34,26 @@ var (
 	// - Line that starts with slash
 	// - followed by non-space characteres,
 	// - (optional) followed by space and arguments
-	commandRegex = regexp.MustCompile(`^/([^\s]+) *?([^\n]*)`)
+	commandRegex = regexp.MustCompile(`(?m)^/([^\s]+)[\t ]*([^\n\r]*)`)
```
Comment (grodrigues3) [inline mungegithub/mungers/matchers/comment/command.go]: I don't speak regex.  @spxtr does this make sense to you/look similar to the prow one?

File: mungegithub/mungers/matchers/comment/command_test.go [hunk 2]
```diff
@@ -25,51 +25,66 @@ import (
...
+			comment:          "/command Command name is upper-cased",
+		},
+		{
+			expectedCommands: []*Command{&Command{Name: "COMMAND", Arguments: "Arguments is trimmed"}},
+			comment:          "/COMMAND     Arguments is trimmed   ",
+		},
+		{
+			expectedCommands: []*Command{&Command{Name: "COMMAND"}},
+			comment:          "Command not at the beginning:\n/COMMAND\nAnd something else...",
 		},
```
Comment (grodrigues3) [inline mungegithub/mungers/matchers/comment/command_test.go]: This checks that we can find commands not at the beginning of the comments but still at the beginning of the line.  Maybe add a test that verifies we ignore commands midway through the line.  And something that shows we ignore two forward slashes entirely (the comment thing)

File: mungegithub/mungers/matchers/comment/command_test.go [hunk 3]
```diff
@@ -25,51 +25,66 @@ import (
...
-			expectedCommand: nil,
-			comment:         "I have nothing to do with a command",
+			expectedCommands: []*Command{},
+			comment:          "I have nothing to do with a command",
 		},
 		{
-			expectedCommand: nil,
-			comment:         " /COMMAND Line can't start with spaces",
+			expectedCommands: []*Command{},
+			comment:          " /COMMAND Line can't start with spaces",
```
Comment (apelisse) [inline mungegithub/mungers/matchers/comment/command_test.go]: @grodrigues3 Doesn't this test what you want?

File: mungegithub/mungers/matchers/comment/interactions.go [hunk 4]
```diff
@@ -41,23 +41,27 @@ type CommandName string
 
 // Match will return true if the comment is a command with the given name
 func (c CommandName) Match(comment *github.IssueComment) bool {
```
Comment (grodrigues3) [inline mungegithub/mungers/matchers/comment/interactions.go]: Update the comment.  It will return true if the comment's body contains a command at the beginning of a line (other text is permitted on other lines)

File: mungegithub/mungers/matchers/comment/command_test.go (hunk 3 above)
Comment (grodrigues3) [inline mungegithub/mungers/matchers/comment/command_test.go]: yeah, just change the name.  Command must be at the beginning of the line.
