### PR TITLE
Fix tide serving invalid JSON.

### LINKED ISSUE #7091: Tide is serving bad JSON data to Deck.
ref: https://github.com/kubeflow/community/issues/20

Tide is improperly serializing its pool data. Here is a sample:
```json
{"Context":"coverage/coveralls",
"Description":"Coverage increased (+0.1%!)(MISSING) to 27.599%!"(MISSING),
"State":"SUCCESS"}
```
Even though this is not valid JSON, `json.Marshal` does not throw an error when emitting this text (?!!) so tide serves it, thinking that it is valid.
https://github.com/kubernetes/test-infra/blob/ef5978825db04c5c161574ad7395831850ab92df/prow/tide/tide.go#L381-L386

I've been able to reproduce the behavior locally in a unit test and it seems like` json.Marshal `doesn't behave well when marshaling `github.com/shurcooL/githubql.String` types with values containing "%" symbols.

I think we will need to make a struct that doesn't use `githubql.String`s and marshal/unmarshal slices of that struct instead of the `[]PullRequest` fields in `tide.Pool`.
Alternatively we could try a different JSON parsers...

Tide's main sync loop is unaffected by this so testing and merging is working as expected, but the "Tide Status" page is not going to show any data until we resolve this or disable tide for the repos that are using the "coverage/coveralls" context. 

/kind bug
/area prow
cc @BenTheElder @kargakis @stevekuznetsov @spxtr

### PR DESCRIPTION
**Pull request by cjwagner**
fixes #7091 
/area prow
/kind bug
/cc @BenTheElder @stevekuznetsov

### CODE REVIEW

File: prow/tide/tide.go [hunk 1]
```diff
@@ -380,10 +380,10 @@ func (c *Controller) ServeHTTP(w http.ResponseWriter, r *http.Request) {
 	defer c.m.Unlock()
 	b, err := json.Marshal(c.pools)
 	if err != nil {
-		c.logger.WithError(err).Error("Decoding JSON.")
+		c.logger.WithError(err).Error("Encoding JSON.")
 		b = []byte("[]")
 	}
-	fmt.Fprintf(w, string(b))
+	fmt.Fprint(w, string(b))
```
Comment (BenTheElder) [inline prow/tide/tide.go]: why not w.Write(b) ?

Comment (cjwagner) [reply prow/tide/tide.go]: I think they should be functionally equivalent. `w.Write(b)` is probably a little faster though.

Fixed and added an error check.

Comment (BenTheElder) [reply prow/tide/tide.go]: yeah, the output here would be the same but it's costlier on top of the unnecessary string conversion.
